import type { Locale } from "@/lib/i18n/routing";

const sources = {
  blood:"https://www.nhlbi.nih.gov/health/blood-tests",
  restore:"https://www.nhsbt.nhs.uk/clinical-trials-unit/trials-and-studies/blood-and-transfusion/restore/",
  follow:"https://www.nhsbt.nhs.uk/component-development-laboratory/our-work/translational-projects/",
  final:"https://bioresource.nihr.ac.uk/news/final-batch-of-red-blood-cells-produced-in-restore",
  protocol:"https://doi.org/10.1136/bmjopen-2025-110183",
  registry:"https://rctportal.mhlw.go.jp/s/detail/um?trial_id=jRCT2051240249",
  hemo:"https://clinicaltrials.gov/study/NCT01881503",
  pfc:"https://www.frontiersin.org/journals/medicine/articles/10.3389/fmed.2026.1874098/full"
};
const copy = {
  en:{titles:["What each approach can replace", "Two trials, different questions"],date:"Evidence checked October 10, 2026",headers:["Approach", "Material and intended function", "Compatibility", "Evidence and clinical status"],note:"An oxygen carrier is not whole blood. Status is specific to the product and indication; these rows are not an efficacy ranking. Scroll horizontally on small screens.", rows:[
    ["Donated red-cell component", "Biological cells; established oxygen transport", "Donor–recipient matching and testing", "Established clinical use; not the same as whole blood"],
    ["Cultured red cells / RESTORE", "Biological young red cells grown from donor stem cells", "Blood-group markers retained; matched recipients", "Phase I mini-dose study; follow-up complete, final comparative results awaited"],
    ["Hemoglobin vesicles / NMU-HbV", "Human hemoglobin inside lipid capsules; oxygen-carrier aim", "No ordinary red-cell ABO surface; reactions still possible", "Phase Ib healthy-volunteer study; protocol is not an efficacy result"],
    ["Cell-free modified hemoglobin / HBOCs", "Chemically modified or engineered hemoglobin", "No ordinary red-cell surface; product-specific safety", "HBOC-201 has an expanded-access record; not FDA marketing approval"],
    ["Perfluorocarbon emulsions", "Fluorinated compounds dissolve oxygen", "Not biological red cells; formulation risks remain", "Product-specific research; much current evidence is preclinical"]],
    trials:[{name:"UK: RESTORE",facts:["Phase I, randomised crossover in healthy volunteers.","2022 launch report: mini-transfusions around 5–10 mL.","Final batch administered by the February 2026 update; follow-up complete.","NHSBT expects results in 2026 or 2027. Longer cell survival is not yet established by final results."]},{name:"Japan: NMU-HbV",facts:["Phase Ib open-label dose-escalation protocol, published January 2026.","Target: 16 healthy volunteers. Planned cohorts: 100, 100, 200 and 400 mL.","Official registry: not recruiting when checked October 10.","Planned doses and registry status do not establish efficacy in bleeding patients or routine approval."]}],source:"Source",design:"Design",update:"Update",status:"Status",trialNote:"Dose volumes refer to different products and study designs. They cannot be compared as measures of benefit or clinical readiness."},
  fr:{titles:["Ce que chaque approche peut remplacer", "Deux essais, des questions différentes"],date:"Preuves vérifiées le 10 octobre 2026",headers:["Approche", "Matériau et fonction visée", "Compatibilité", "Preuves et statut clinique"],note:"Un transporteur d’oxygène n’est pas du sang complet. Le statut dépend du produit et de l’indication ; aucun classement d’efficacité. Défilement horizontal sur petit écran.",rows:[
    ["Globules rouges donnés", "Cellules biologiques ; transport d’oxygène établi", "Appariement et tests donneur–receveur", "Usage clinique établi ; distinct du sang complet"],
    ["Globules cultivés / RESTORE", "Jeunes cellules issues de cellules souches de donneurs", "Marqueurs conservés ; receveurs compatibles", "Mini-dose de phase I ; suivi terminé, résultats comparatifs attendus"],
    ["Vésicules / NMU-HbV", "Hémoglobine humaine en capsules lipidiques", "Pas de surface ABO normale ; réactions possibles", "Phase Ib chez des volontaires sains ; protocole sans résultat d’efficacité"],
    ["Hémoglobine modifiée acellulaire", "Hémoglobine modifiée ou issue d’ingénierie", "Pas de surface normale ; sécurité propre au produit", "HBOC-201 : dossier d’accès élargi, pas d’autorisation commerciale FDA"],
    ["Émulsions de perfluorocarbures", "Composés fluorés dissolvant l’oxygène", "Pas des globules biologiques ; risques de formulation", "Recherche spécifique ; beaucoup de preuves actuelles précliniques"]],trials:[{name:"Royaume-Uni : RESTORE",facts:["Phase I randomisée et croisée chez des volontaires sains.","Lancement 2022 : mini-transfusions d’environ 5–10 mL.","Dernier lot administré selon la mise à jour de février 2026 ; suivi terminé.","NHSBT attend les résultats en 2026 ou 2027. La survie prolongée n’est pas encore un résultat final établi."]},{name:"Japon : NMU-HbV",facts:["Protocole de phase Ib ouvert avec escalade, publié en janvier 2026.","Cible : 16 volontaires sains. Cohortes prévues : 100, 100, 200 et 400 mL.","Registre officiel : pas de recrutement au 10 octobre.","Ni doses prévues ni statut ne prouvent efficacité hémorragique ou autorisation de routine."]}],source:"Source",design:"Protocole",update:"Mise à jour",status:"Statut",trialNote:"Les volumes concernent des produits et protocoles distincts. Ils ne mesurent pas comparativement bénéfice ou maturité clinique."},
  es:{titles:["Qué puede reemplazar cada enfoque", "Dos ensayos, preguntas distintas"],date:"Pruebas verificadas el 10 de octubre de 2026",headers:["Enfoque", "Material y función prevista", "Compatibilidad", "Pruebas y situación clínica"],note:"Un transportador de oxígeno no es sangre completa. El estado depende del producto e indicación; no es un ranking de eficacia. Desplace horizontalmente en pantallas pequeñas.",rows:[
    ["Glóbulos rojos donados", "Células biológicas; transporte establecido", "Compatibilidad y pruebas entre donante y receptor", "Uso clínico establecido; distinto de sangre completa"],
    ["Células cultivadas / RESTORE", "Células jóvenes de células madre de donantes", "Conservan marcadores; receptores compatibles", "Minidosis de fase I; seguimiento terminado, resultados finales pendientes"],
    ["Vesículas / NMU-HbV", "Hemoglobina humana en cápsulas lipídicas", "Sin superficie ABO normal; posibles reacciones", "Fase Ib en sanos; protocolo no es resultado de eficacia"],
    ["Hemoglobina modificada acelular", "Hemoglobina modificada o diseñada", "Sin superficie normal; seguridad específica", "HBOC-201: registro de acceso ampliado, no aprobación comercial FDA"],
    ["Emulsiones de perfluorocarbonos", "Compuestos fluorados disuelven oxígeno", "No son células; persisten riesgos de formulación", "Investigación específica; gran parte de evidencia actual preclínica"]],trials:[{name:"Reino Unido: RESTORE",facts:["Fase I aleatorizada y cruzada en voluntarios sanos.","Anuncio 2022: minitransfusiones de unos 5–10 mL.","Último lote administrado según actualización de febrero de 2026; seguimiento terminado.","NHSBT espera resultados en 2026 o 2027. Mayor supervivencia no está establecida por resultados finales."]},{name:"Japón: NMU-HbV",facts:["Protocolo abierto de escalada de fase Ib, publicado en enero de 2026.","Objetivo: 16 voluntarios sanos. Cohortes previstas: 100, 100, 200 y 400 mL.","Registro oficial: sin reclutamiento al verificar el 10 de octubre.","Dosis previstas y estado no prueban eficacia en hemorragias ni aprobación rutinaria."]}],source:"Fuente",design:"Diseño",update:"Actualización",status:"Estado",trialNote:"Volúmenes de productos y diseños distintos. No comparan beneficio ni preparación clínica."},
  ar:{titles:["ما الذي يستبدله كل نهج؟", "تجربتان بأسئلة مختلفة"],date:"أدلة جرى التحقق منها في 10 أكتوبر 2026",headers:["النهج", "المادة والوظيفة المستهدفة", "التوافق", "الدليل والوضع السريري"],note:"ناقل الأكسجين ليس دماً كاملاً. يخص الوضع المنتج والاستخدام، ولا يمثل الجدول ترتيب فعالية. مرر أفقياً على الشاشة الصغيرة.",rows:[
    ["خلايا حمراء متبرع بها", "خلايا بيولوجية؛ نقل أكسجين راسخ", "توافق وفحوص بين المتبرع والمتلقي", "استخدام سريري راسخ؛ يختلف عن الدم الكامل"],
    ["خلايا مزروعة / RESTORE", "خلايا شابة من خلايا جذعية لمتبرعين", "تحتفظ بعلامات الفصائل؛ متلقون متوافقون", "جرعات صغيرة من المرحلة الأولى؛ انتهت المتابعة وتنتظر النتائج النهائية"],
    ["حويصلات / NMU-HbV", "هيموغلوبين بشري داخل كبسولات دهنية", "دون سطح ABO المعتاد؛ التفاعلات ممكنة", "مرحلة Ib لدى أصحاء؛ البروتوكول ليس نتيجة فعالية"],
    ["هيموغلوبين معدل غير خلوي", "هيموغلوبين معدل كيميائياً أو مهندس", "دون سطح خلوي طبيعي؛ سلامة خاصة بكل منتج", "سجل إتاحة موسعة لـHBOC-201، وليس اعتماداً تجارياً من FDA"],
    ["مستحلبات البيرفلوروكربون", "مركبات مفلورة تذيب الأكسجين", "ليست خلايا بيولوجية؛ مخاطر التركيبة قائمة", "بحث خاص بالمنتج؛ الكثير من الأدلة الحالية ما قبل سريري"]],trials:[{name:"بريطانيا: RESTORE",facts:["مرحلة أولى عشوائية ومتقاطعة لدى متطوعين أصحاء.","إعلان 2022: جرعات صغيرة تقارب 5–10 مل.","أعطيت آخر دفعة وفق تحديث فبراير 2026؛ انتهت المتابعة.","تتوقع NHSBT النتائج في 2026 أو 2027. لم يثبت البقاء الأطول بنتائج نهائية بعد."]},{name:"اليابان: NMU-HbV",facts:["بروتوكول مرحلة Ib مفتوح لتصعيد الجرعات، نشر في يناير 2026.","الهدف: 16 متطوعاً صحيحاً. الجرعات المخططة: 100 و100 و200 و400 مل.","السجل الرسمي: لا تجنيد عند التحقق في 10 أكتوبر.","الجرعات المخططة والحالة لا تثبت فعالية النزف أو اعتماداً روتينياً."]}],source:"المصدر",design:"التصميم",update:"التحديث",status:"الحالة",trialNote:"أحجام جرعات لمنتجات وتصميمات مختلفة. لا تقارن الفائدة أو الجاهزية السريرية."}
};

export function ArtificialBloodGraphics({locale,kind}:{locale:Locale;kind:"comparison"|"trials"}) {
  const t=copy[locale],id=`artificial-blood-${kind}`,isComparison=kind==="comparison";
  const linkStyle="underline decoration-white/40 underline-offset-4 hover:text-[#e9bd65] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#e9bd65]";
  const rowSources=[sources.blood,sources.restore,sources.protocol,sources.hemo,sources.pfc];
  return <figure id={id} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={`${id}-title`} style={{display:"flow-root"}} className="my-8 min-w-0 scroll-mt-28 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
    <p className="mb-3 text-xs font-bold uppercase tracking-wider text-[#FF1A1A]">PRESDA Data Graphics</p>
    <figcaption id={`${id}-title`} className="text-xl font-bold text-[#e9bd65]">{t.titles[isComparison?0:1]}</figcaption>
    <p className="mt-3 text-xs text-white/70">{t.date}</p>
    <p className="mt-3 text-sm leading-relaxed text-white/80">{isComparison?t.note:t.trialNote}</p>
    {isComparison?<div role="region" aria-label={t.titles[0]} tabIndex={0} className="mt-5 overflow-x-auto focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#e9bd65]">
      <table className="w-full min-w-[720px] border-collapse text-sm">
        <caption className="sr-only">{t.titles[0]}. {t.note}</caption>
        <thead><tr>{t.headers.map(h=><th key={h} scope="col" className="border-b border-white/25 p-3 text-start">{h}</th>)}</tr></thead>
        <tbody>{t.rows.map((r,i)=><tr key={i}>{r.map((cell,j)=>j===0?<th key={j} scope="row" className="border-b border-white/15 p-3 text-start font-medium"><span>{cell}</span><a href={rowSources[i]} className={`mt-2 block text-xs ${linkStyle}`}>{t.source}</a></th>:<td key={j} className="border-b border-white/15 p-3 align-top leading-relaxed">{cell}</td>)}</tr>)}</tbody>
      </table>
    </div>:<div className="mt-5 grid gap-5 md:grid-cols-2">{t.trials.map((trial,i)=><section key={trial.name} className="min-w-0 rounded-lg border border-white/20 p-4"><h3 className="font-bold text-[#e9bd65]"><bdi>{trial.name}</bdi></h3><ul className="mt-4 list-disc space-y-3 ps-5 text-sm leading-relaxed">{trial.facts.map(f=><li key={f}>{f}</li>)}</ul><div className="mt-4 flex flex-wrap gap-4 text-xs"><a href={i===0?sources.restore:sources.protocol} className={linkStyle}>{t.design}</a><a href={i===0?sources.final:sources.registry} className={linkStyle}>{t.update}</a><a href={i===0?sources.follow:sources.registry} className={linkStyle}>{t.status}</a></div></section>)}</div>}
  </figure>;
}
