import type { Locale } from "@/lib/i18n/routing";
import { bryanSources as s } from "@/data/bryanJohnsonArticle";
const copy = {
 en:{routine:"A day in his published routine",note:"Self-described schedule, reviewed October 2, 2026. Approximate times, not a medical recommendation or a time-to-scale chart.",steps:["~5 a.m. | Wake and measure body composition","6 a.m. | Strength, cardio, balance and flexibility","~Noon | Final meal","7:30 p.m. | Family, friends and winding down","8:30 p.m. | Bedtime"],evidence:"Three different kinds of evidence",cards:[["Established health benefits","Regular physical activity and muscle strengthening. This supports exercise, not the complete Blueprint package."],["Promising research signals","Calorie restriction changed one aging measure in CALERIE, not all clocks. Human lifespan extension was not established."],["Experimental longevity claims","Young plasma and personal drug or gene-therapy experiments do not establish rejuvenation. FDA reports no established anti-aging benefit of young plasma."]],foot:"Qualitative editorial guide, not a numerical score or a claim that every intervention in a group has equal evidence.",source:"Source"},
 fr:{routine:"Une journée selon son programme publié",note:"Emploi du temps déclaré, consulté le 2 octobre 2026. Heures approximatives, sans recommandation médicale ni échelle de durée.",steps:["Vers 5 h | Réveil et composition corporelle","6 h | Force, cardio, équilibre et souplesse","Vers midi | Dernier repas","19 h 30 | Proches et retour au calme","20 h 30 | Coucher"],evidence:"Trois niveaux à distinguer",cards:[["Bénéfices établis pour la santé","Activité physique et renforcement musculaire réguliers. Cela soutient l’exercice, pas tout le programme Blueprint."],["Signaux de recherche prometteurs","La restriction calorique a modifié une mesure dans CALERIE, pas toutes les horloges. L’allongement de la vie humaine n’est pas établi."],["Promesses de longévité expérimentales","Plasma jeune, médicaments et thérapies géniques testés individuellement ne prouvent pas le rajeunissement. La FDA ne constate pas de bénéfice anti-âge établi du plasma jeune."]],foot:"Repères éditoriaux qualitatifs, sans note chiffrée ni équivalence supposée entre toutes les interventions d’un groupe.",source:"Source"},
 es:{routine:"Un día según su rutina publicada",note:"Horario declarado, revisado el 2 de octubre de 2026. Horas aproximadas, sin recomendación médica ni escala proporcional de duración.",steps:["Hacia las 5:00 | Despertar y medir composición corporal","6:00 | Fuerza, cardio, equilibrio y flexibilidad","Hacia mediodía | Última comida","19:30 | Familia, amigos y relajación","20:30 | Acostarse"],evidence:"Tres tipos de evidencia diferentes",cards:[["Beneficios establecidos para la salud","Actividad física y fortalecimiento muscular regulares. Respalda el ejercicio, no todo el paquete Blueprint."],["Señales de investigación prometedoras","La restricción calórica modificó una medida en CALERIE, no todos los relojes. No se estableció una vida humana más larga."],["Afirmaciones experimentales de longevidad","El plasma joven y los experimentos personales con fármacos o terapia génica no prueban rejuvenecimiento. La FDA no reconoce beneficios antienvejecimiento establecidos del plasma joven."]],foot:"Guía editorial cualitativa, sin puntuación numérica ni equivalencia entre todas las intervenciones de una categoría.",source:"Fuente"},
 ar:{routine:"يوم في برنامجه المنشور",note:"جدول يصفه بنفسه، روجع في 2 أكتوبر 2026. أوقات تقريبية، وليس توصية طبية أو رسما تتناسب مسافاته مع المدة.",steps:["نحو الخامسة صباحا | الاستيقاظ وقياس تركيب الجسم","السادسة صباحا | القوة واللياقة والتوازن والمرونة","نحو الظهر | آخر وجبة","السابعة والنصف مساء | الأهل والأصدقاء والاسترخاء","الثامنة والنصف مساء | النوم"],evidence:"ثلاثة أنواع مختلفة من الأدلة",cards:[["فوائد صحية مثبتة","النشاط البدني وتقوية العضلات بانتظام. هذا يدعم الرياضة، لا حزمة بلوبرينت بأكملها."],["إشارات بحثية واعدة","غيّر تقييد السعرات أحد مقاييس الشيخوخة في CALERIE، لا جميع الساعات. لم تثبت إطالة حياة البشر."],["ادعاءات تجريبية لطول العمر","البلازما الشابة والتجارب الشخصية بالأدوية والعلاج الجيني لا تثبت استعادة الشباب. لا تقر FDA بفائدة مثبتة للبلازما الشابة ضد الشيخوخة."]],foot:"دليل تحريري نوعي، لا درجة رقمية ولا ادعاء بتساوي الأدلة لكل تدخل داخل الفئة.",source:"المصدر"}
};
export function BryanJohnsonGraphics({locale,kind}:{locale:Locale;kind:"routine"|"evidence"}){
 const c=copy[locale];const refs=kind==="routine"?[s.protocol,s.evening]:[s.who,s.calorie,s.fda];
 return <figure id={`bryan-${kind}`} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={`bryan-${kind}-title`} className="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
 <figcaption id={`bryan-${kind}-title`} className="font-display text-xl font-bold sm:text-2xl">{kind==="routine"?c.routine:c.evidence}</figcaption>
 {kind==="routine"?<><p className="mt-3 text-sm text-white/75">{c.note}</p><ol className="my-5 space-y-4 border-s-2 border-[#e9bd65] ps-5">{c.steps.map((step,i)=><li key={step} className="text-sm leading-relaxed"><span className="me-2 font-bold text-[#e9bd65]">{i+1}.</span>{step}</li>)}</ol></>:<><div className="my-5 grid gap-4">{c.cards.map(([title,text],i)=><section key={title} className="border-s-4 border-[#e9bd65] ps-4"><h3 className="font-bold text-base">{i+1}. {title}</h3><p className="mt-2 text-sm leading-relaxed text-white/85">{text}</p><a className="mt-2 inline-block text-sm text-[#e9bd65] underline" href={refs[i].url}>{c.source}: {i+1}</a></section>)}</div><p className="text-sm text-white/75">{c.foot}</p></>}
 {kind==="routine"&&<p className="flex flex-wrap gap-4 text-sm">{refs.map((ref,i)=><a key={ref.url} href={ref.url} className="text-[#e9bd65] underline">{c.source} {i+1}</a>)}</p>}
 <p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
 </figure>;
}
