import type { Locale } from "@/lib/i18n/routing";

// ACS Cancer Facts & Figures 2026, Table 7, all races/ethnicities, all stages.
// Rounded published percentages: diagnoses 1975–1977, 1995–1997, 2015–2021.
// Historical SEER 9 vs recent SEER 21 excluding Illinois. No interpolation.
const rows = [[49,63,70],[25,32,62],[34,48,68],[68,97,98],[50,62,79],[47,56,74],[75,87,92],[72,84,89],[83,96,95],[50,61,65],[12,15,28],[3,4,13],[23,32,33]];
// Table 8: local vs distant, not randomized comparisons or personal predictions.
const stages = [[99,33],[91,15],[65,10],[44,3]];
const source = "https://www.cancer.org/content/dam/cancer-org/research/cancer-facts-and-statistics/annual-cancer-facts-and-figures/2026/2026-cancer-facts-and-figures.pdf";
const milestoneSource = "https://www.cancer.gov/research/progress/250-years-milestones";
const copy = {
  en:{title:"Five decades, very different outcomes",note:"U.S. five-year relative survival (%), all stages. Selected sites, not an exhaustive ranking. Diagnosis periods, not survival forecasts for 2026.",names:["All cancers combined","Myeloma","Leukemia","Prostate","Kidney and renal pelvis","Non-Hodgkin lymphoma","Female breast","Hodgkin lymphoma","Testis","Colon and rectum","Lung and bronchus","Pancreas","Brain and other nervous system"],old:"1975–1977",mid:"1995–1997",recent:"2015–2021",gain:"Change in percentage points",table:"Full data table",type:"Cancer site",caveat:"Relative survival adjusts for background mortality, not recurrence. Historical SEER 9 and recent SEER 21 coverage differ. All ages; brain/nervous-system data are not glioblastoma-specific. Source values are rounded.",stageTitle:"Same cancer, different stage",stageNote:"U.S. five-year relative survival (%), diagnoses 2015–2021. Localized: confined to the original organ. Distant: spread to remote sites. These are group outcomes, not proof of screening benefit.",stageNames:["Female breast","Colon and rectum","Lung and bronchus","Pancreas"],local:"Localized",distant:"Distant",stageCaveat:"The breast value is greater than 99%, not exactly 99%. Summary registry stages differ from clinical staging systems.",timelineTitle:"Selected treatment milestones",timelineNote:"U.S. FDA approvals and a clinical research milestone. Ordered events, not an equally spaced time scale or a claim that one drug caused a population trend.",events:["1978: Tamoxifen approved for breast cancer","1998: Trastuzumab approved for HER2-positive metastatic breast cancer","2001: Imatinib trial demonstrates activity in chronic myeloid leukemia","2011: Ipilimumab approved for advanced melanoma","2017: First CAR-T approvals for selected blood cancers"],source:"Source"},
  fr:{title:"Cinq décennies, des résultats très différents",note:"Survie relative à cinq ans aux États-Unis (%), tous stades. Sélection, pas classement exhaustif. Périodes de diagnostic, sans prédiction pour 2026.",names:["Tous cancers réunis","Myélome","Leucémies","Prostate","Rein et bassinet","Lymphome non hodgkinien","Sein féminin","Lymphome de Hodgkin","Testicule","Côlon et rectum","Poumon et bronches","Pancréas","Cerveau et système nerveux"],old:"1975–1977",mid:"1995–1997",recent:"2015–2021",gain:"Variation en points de pourcentage",table:"Tableau complet",type:"Localisation",caveat:"Survie ajustée sur la mortalité habituelle, pas sur les rechutes. Couverture SEER 9 historique et SEER 21 récente différente. Tous âges ; cerveau et système nerveux ne désignent pas le seul glioblastome. Valeurs arrondies.",stageTitle:"Même cancer, autre stade",stageNote:"Survie relative à cinq ans aux États-Unis (%), diagnostics 2015–2021. Localisé : limité à l’organe initial. Distant : sites éloignés. Résultats de groupes, sans preuve du bénéfice d’un dépistage.",stageNames:["Sein féminin","Côlon et rectum","Poumon et bronches","Pancréas"],local:"Localisé",distant:"Distant",stageCaveat:"Le chiffre du sein dépasse 99 %, il n’est pas exactement 99 %. Les stades de registre diffèrent des systèmes cliniques.",timelineTitle:"Quelques étapes thérapeutiques",timelineNote:"Autorisations américaines et étape de recherche clinique. Événements ordonnés, sans échelle de durées égales ni attribution d’une tendance à un seul médicament.",events:["1978 : tamoxifène autorisé pour le cancer du sein","1998 : trastuzumab autorisé pour le sein métastatique HER2 positif","2001 : essai montrant l’activité de l’imatinib dans la leucémie myéloïde chronique","2011 : ipilimumab autorisé pour le mélanome avancé","2017 : premières autorisations CAR-T dans certains cancers du sang"],source:"Source"},
  es:{title:"Cinco décadas, resultados muy distintos",note:"Supervivencia relativa a cinco años en EE. UU. (%), todos los estadios. Selección, no clasificación exhaustiva. Períodos de diagnóstico, no predicciones para 2026.",names:["Todos los cánceres","Mieloma","Leucemias","Próstata","Riñón y pelvis renal","Linfoma no Hodgkin","Mama femenina","Linfoma de Hodgkin","Testículo","Colon y recto","Pulmón y bronquios","Páncreas","Cerebro y otros tejidos nerviosos"],old:"1975–1977",mid:"1995–1997",recent:"2015–2021",gain:"Cambio en puntos porcentuales",table:"Tabla completa",type:"Localización",caveat:"Ajuste por mortalidad habitual, no por recaída. Coberturas históricas SEER 9 y recientes SEER 21 distintas. Todas las edades; cerebro y tejidos nerviosos no equivale a glioblastoma. Valores redondeados.",stageTitle:"Mismo cáncer, distinto estadio",stageNote:"Supervivencia relativa a cinco años en EE. UU. (%), diagnósticos 2015–2021. Localizado: órgano inicial. Distante: otros sitios remotos. Resultados colectivos, no prueba del beneficio del cribado.",stageNames:["Mama femenina","Colon y recto","Pulmón y bronquios","Páncreas"],local:"Localizado",distant:"Distante",stageCaveat:"Mama supera 99%, no es exactamente 99%. Las categorías registrales difieren de los sistemas clínicos.",timelineTitle:"Hitos terapéuticos seleccionados",timelineNote:"Autorizaciones estadounidenses y un hito de investigación clínica. Orden cronológico, sin escala temporal uniforme ni atribución de tendencias a un solo fármaco.",events:["1978: tamoxifeno autorizado para cáncer de mama","1998: trastuzumab autorizado para mama metastásica HER2 positiva","2001: ensayo demuestra actividad de imatinib en leucemia mieloide crónica","2011: ipilimumab autorizado para melanoma avanzado","2017: primeras autorizaciones CAR-T para ciertos cánceres sanguíneos"],source:"Fuente"},
  ar:{title:"خمسة عقود ونتائج مختلفة جذريا",note:"البقاء النسبي لخمس سنوات في الولايات المتحدة (%)، جميع المراحل. فئات مختارة لا ترتيب شامل. فترات تشخيص وليست توقعات لعام 2026.",names:["جميع السرطانات","الورم النقوي","ابيضاض الدم","البروستاتا","الكلى والحويضة","اللمفوما اللاهودجكينية","الثدي لدى النساء","لمفوما هودجكين","الخصية","القولون والمستقيم","الرئة والشعب","البنكرياس","الدماغ والجهاز العصبي"],old:"1975–1977",mid:"1995–1997",recent:"2015–2021",gain:"التغير بالنقاط المئوية",table:"جدول البيانات الكامل",type:"موضع السرطان",caveat:"البقاء معدل للوفيات المعتادة وليس للانتكاس. تختلف تغطية SEER 9 القديمة عن SEER 21 الحديثة. جميع الأعمار؛ أرقام الدماغ ليست خاصة بالورم الأرومي الدبقي. القيم مقربة.",stageTitle:"السرطان نفسه ومرحلة مختلفة",stageNote:"البقاء النسبي لخمس سنوات في الولايات المتحدة (%) لتشخيصات 2015–2021. موضعي: داخل عضو المنشأ. بعيد: انتقال إلى مواقع نائية. نتائج جماعات وليست إثباتا لفائدة التحري.",stageNames:["الثدي لدى النساء","القولون والمستقيم","الرئة والشعب","البنكرياس"],local:"موضعي",distant:"انتشار بعيد",stageCaveat:"قيمة الثدي أكبر من 99% وليست 99% بالضبط. تختلف فئات السجلات عن نظم المراحل السريرية.",timelineTitle:"محطات علاجية مختارة",timelineNote:"اعتمادات أمريكية ومحطة بحث سريري. أحداث مرتبة لا مقياس لفترات متساوية ولا ادعاء بأن دواء واحد سبب اتجاه السكان.",events:["1978: اعتماد تاموكسيفين لسرطان الثدي","1998: اعتماد تراستوزوماب لسرطان الثدي المنتشر الإيجابي لـHER2","2001: تجربة تظهر فعالية إيماتينيب في ابيضاض الدم النقوي المزمن","2011: اعتماد إيبيليموماب للميلانوما المتقدمة","2017: أول اعتمادات CAR-T لبعض سرطانات الدم"],source:"المصدر"}
};

export function CancerProgressGraphics({locale,kind}:{locale:Locale;kind:"survival"|"stage"|"milestones"}) {
  const c=copy[locale],id=`cancer-${kind}`,isStage=kind==="stage",timeline=kind==="milestones";
  const names=isStage?c.stageNames:c.names;
  return <figure id={id} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={`${id}-title`} className="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
    <figcaption id={`${id}-title`} className="font-display text-xl font-bold sm:text-2xl">{timeline?c.timelineTitle:isStage?c.stageTitle:c.title}</figcaption>
    <p className="mt-3 text-sm leading-relaxed text-white/75">{timeline?c.timelineNote:isStage?c.stageNote:c.note}</p>
    {timeline ? <ol className="mt-6 space-y-4 border-s-2 border-[#e9bd65]/60 ps-5">{c.events.map(event=><li key={event} className="text-sm leading-relaxed">{event}</li>)}</ol> : <>
      <div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-xs"><span className="text-[#e9bd65]">● {isStage?c.local:c.old}</span><span className="text-[#ff6060]">■ {isStage?c.distant:c.recent}</span></div>
      <div aria-hidden="true" className="mt-3 flex justify-between text-xs text-white/50"><span>0%</span><span>100%</span></div>
      <div className="mt-5 space-y-5">{names.map((name,i)=>{
        const a=isStage?stages[i][0]:rows[i][0],b=isStage?stages[i][1]:rows[i][2],localValue=isStage&&i===0?">99":String(a);
        return <div key={name}><div className="mb-2 flex flex-wrap justify-between gap-2 text-sm"><span className="font-semibold">{name}</span><span className="flex gap-3 tabular-nums"><span className="text-[#e9bd65]"><bdi>{localValue}%</bdi></span><span className="text-[#ff6060]"><bdi>{b}%</bdi></span>{!isStage&&<span className="text-white/60" title={c.gain}><bdi>+{b-a}</bdi></span>}</span></div>
          <div aria-hidden="true" className="space-y-1.5"><div className="h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#e9bd65]" style={{width:`${a}%`}} /></div><div className="h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#ff6060]" style={{width:`${b}%`}} /></div></div>
        </div>;
      })}</div>
      <p className="mt-4 text-xs text-white/65">{isStage?c.stageCaveat:c.gain+": +"}</p>
      <details className="mt-5"><summary className="cursor-pointer text-sm text-[#e9bd65] underline">{c.table}</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-start text-xs"><caption className="sr-only">{isStage?c.stageTitle:c.title}</caption><thead><tr>{[c.type,isStage?c.local:c.old,...(isStage?[]:[c.mid]),isStage?c.distant:c.recent].map(h=><th key={h} scope="col" className="p-2 text-start font-semibold">{h}</th>)}</tr></thead><tbody>{names.map((name,i)=><tr key={name} className="border-t border-white/10"><th scope="row" className="p-2 text-start font-normal">{name}</th>{(isStage?stages[i]:rows[i]).map((v,j)=><td key={j} className="p-2 tabular-nums"><bdi>{isStage&&i===0&&j===0?">99":v}%</bdi></td>)}</tr>)}</tbody></table></div></details>
      {!isStage&&<p className="mt-4 text-xs leading-relaxed text-white/65">{c.caveat}</p>}
    </>}
    <p className="mt-5 text-xs leading-relaxed">{c.source}: <a className="text-[#e9bd65] underline" href={timeline?milestoneSource:source}>{timeline?"NCI":"ACS 2026"}{!timeline&&` (${isStage?"8":"7"})`}</a></p>
    <p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
  </figure>;
}
