import type { Locale } from "@/lib/i18n/routing";

// Ages before present, not calendar dates. Source: Hublin et al. 2026, Fig. 1/dating;
// Richter et al. 2017, abstract. No inferred ancestry edges or proportional spacing.
const copy = {
  en: { title:"One region, very different evolutionary moments", note:"Approximate ages before present. Ordered evidence, not a direct ancestral chain or a scale of equal durations.", ages:["About 1.3 million years","773,000 ± 4,000 years","315,000 ± 34,000 years"], names:["Thomas Quarry I: older tool-bearing locality","Thomas Quarry I: Grotte à Hominidés","Jebel Irhoud: separate site"], details:["Acheulean archaeology. Not the age of the hominin assemblage discussed here.","Early Homo fossils. Magnetostratigraphy anchors the deposits near a magnetic reversal.","Early Homo sapiens. Thermoluminescence dating of associated heated flints."], title2:"Evidence, interpretation, open questions", levels:["Established observations","Researchers’ interpretation","Not established"], facts:["Jaws, teeth and vertebrae; a sedimentary age framework near 773,000 years.","An African population close to the roots of later Homo lineages.","A direct ancestor, definitive species assignment, or a single birthplace of modern humans."], source:"Scientific sources" },
  fr: { title:"Une région, des moments évolutifs très différents", note:"Âges approximatifs avant le présent. Repères ordonnés, sans filiation directe ni échelle de durées égales.", ages:["Environ 1,3 million d’années","773 000 ± 4 000 ans","315 000 ± 34 000 ans"], names:["Thomas I : localité ancienne à outils","Thomas I : Grotte à Hominidés","Jebel Irhoud : autre site"], details:["Archéologie acheuléenne. Ce n’est pas l’âge de l’assemblage humain décrit ici.","Fossiles anciens de Homo. Dépôts datés près d’une inversion magnétique.","Homo sapiens anciens. Thermoluminescence de silex chauffés associés."], title2:"Observations, interprétation, questions ouvertes", levels:["Observations établies","Interprétation des chercheurs","Non établi"], facts:["Mandibules, dents et vertèbres ; cadre sédimentaire proche de 773 000 ans.","Une population africaine proche des racines de lignées ultérieures de Homo.","Un ancêtre direct, une espèce définitive ou un berceau unique des humains modernes."], source:"Sources scientifiques" },
  es: { title:"Una región, momentos evolutivos muy distintos", note:"Edades aproximadas antes del presente. Evidencia ordenada, sin cadena ancestral directa ni escala de duraciones iguales.", ages:["Unos 1,3 millones de años","773.000 ± 4.000 años","315.000 ± 34.000 años"], names:["Thomas I: localidad antigua con herramientas","Thomas I: Grotte à Hominidés","Jebel Irhoud: otro yacimiento"], details:["Arqueología achelense. No es la edad del conjunto de homininos descrito aquí.","Fósiles tempranos de Homo. Depósitos próximos a una inversión magnética.","Homo sapiens tempranos. Termoluminiscencia de sílex calentados asociados."], title2:"Pruebas, interpretación y preguntas abiertas", levels:["Observaciones establecidas","Interpretación de los investigadores","No demostrado"], facts:["Mandíbulas, dientes y vértebras; un marco sedimentario próximo a 773.000 años.","Una población africana cercana a las raíces de linajes posteriores de Homo.","Un ancestro directo, una especie definitiva o una cuna única de humanos modernos."], source:"Fuentes científicas" },
  ar: { title:"منطقة واحدة ولحظات تطورية مختلفة", note:"أعمار تقريبية قبل الحاضر. ترتيب للأدلة، وليس سلسلة نسب مباشرة أو مقياسا لفترات متساوية.", ages:["نحو 1.3 مليون سنة","773 ألف سنة ± 4 آلاف سنة","315 ألف سنة ± 34 ألف سنة"], names:["توماس الأولى: موقع أدوات أقدم","توماس الأولى: مغارة أشباه البشر","جبل إيغود: موقع مختلف"], details:["آثار أشولية. ليس هذا عمر مجموعة أشباه البشر موضوع المقال.","أحافير قديمة من جنس الإنسان. رواسب قرب انقلاب المجال المغناطيسي.","أفراد مبكرون من الإنسان العاقل. تأريخ الصوان المسخن المرتبط بهم بالتلألؤ الحراري."], title2:"الأدلة والتفسير والأسئلة المفتوحة", levels:["ملاحظات مثبتة","تفسير الباحثين","غير مثبت"], facts:["فكوك وأسنان وفقرات وإطار رسوبي بعمر يقارب 773 ألف سنة.","جماعة أفريقية قريبة من جذور سلالات لاحقة من جنس الإنسان.","سلف مباشر أو تصنيف نوعي نهائي أو موطن واحد لنشأة البشر المعاصرين."], source:"المصادر العلمية" }
};

export function CasablancaFossilsGraphics({locale,kind}:{locale:Locale;kind:"chronology"|"evidence"}) {
  const c=copy[locale],timeline=kind==="chronology",id=`casablanca-${kind}`;
  return <figure id={id} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={`${id}-title`} className="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
    <figcaption id={`${id}-title`} className="font-display text-xl font-bold sm:text-2xl">{timeline?c.title:c.title2}</figcaption>
    {timeline && <p className="mt-3 text-sm leading-relaxed text-white/75">{c.note}</p>}
    <ol className="mt-6 space-y-5 border-s-2 border-[#e9bd65]/60 ps-5">{(timeline?c.names:c.levels).map((name,i)=><li key={name}>
      {timeline && <p className="text-sm font-bold text-[#e9bd65]">{c.ages[i]}</p>}
      <h3 className="mt-1 font-display text-lg font-bold">{name}</h3>
      <p className="mt-1 text-sm leading-relaxed text-white/80">{timeline?c.details[i]:c.facts[i]}</p>
    </li>)}</ol>
    <p className="mt-5 text-xs leading-relaxed">{c.source}: <a className="text-[#e9bd65] underline" href="https://www.nature.com/articles/s41586-025-09914-y">Hublin et al. (2026)</a>{timeline && <>, <a className="text-[#e9bd65] underline" href="https://www.nature.com/articles/nature22335">Richter et al. (2017)</a></>}</p>
    <p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
  </figure>;
}
