import type { Locale } from "@/lib/i18n/routing";
import { chinaRoboticsSources as s } from "@/data/chinaRoboticsArticle";
const copy={
 en:{share:"China receives most new industrial robots",shareNote:"Share of worldwide industrial robot installations, 2025. These are annual additions, not operating stock.",china:"China",rest:"Rest of world",shareEnd:"China: 354,000 installations. The remaining 41% is calculated as 100% minus IFR's rounded 59%.",density:"Largest market does not mean highest density",densityNote:"Industrial robots per 10,000 manufacturing employees, 2024. All five countries use IFR's April 2026 release.",countries:["South Korea","Germany","Japan","United States","China"],densityEnd:"China's denominator was revised using updated workforce data. Do not splice these values into older published Chinese density series. Bars start at zero.",status:"Four kinds of evidence, not one robot workforce",statusNote:"Selected examples reviewed October 3, 2026. This is not a census or a ranking of manufacturers.",rows:[["Operating production","BYD: conventional automation observed in a battery factory. CATL: Galbot S1 production-line use reported by the company, without an independent performance audit."],["Factory trials","Xiaomi's July 2026 task results and Zeekr's humanoid trials. A task success rate is not a plant-wide productivity measure."],["Demonstrations","World Robot Conference performances show capabilities under particular conditions, not sustained industrial employment."],["Announced future capacity","UBTECH's November 2025 release combines deliveries with future capacity targets. Capacity and orders are not verified working hours."]],source:"Sources",table:"Accessible data table",country:"Country",value:"Robots per 10,000 employees"},
 fr:{share:"La Chine accueille la majorité des nouveaux robots industriels",shareNote:"Part des installations mondiales de robots industriels en 2025. Il s'agit d'ajouts annuels, pas du parc en service.",china:"Chine",rest:"Reste du monde",shareEnd:"Chine : 354 000 installations. Les 41 % restants correspondent à 100 % moins les 59 % arrondis de l'IFR.",density:"Le premier marché n'a pas la plus forte densité",densityNote:"Robots industriels pour 10 000 salariés de l'industrie manufacturière, 2024. Même publication IFR d'avril 2026 pour les cinq pays.",countries:["Corée du Sud","Allemagne","Japon","États-Unis","Chine"],densityEnd:"Le dénominateur chinois a été révisé avec de nouvelles données d'emploi. Ne pas raccorder ces valeurs aux anciennes séries chinoises. Les barres partent de zéro.",status:"Quatre niveaux de preuve à distinguer",statusNote:"Exemples choisis, vérifiés le 3 octobre 2026. Ni recensement ni classement des fabricants.",rows:[["Production en service","BYD : automatisation classique observée dans une usine de batteries. CATL : utilisation de Galbot S1 sur ses lignes annoncée par l'entreprise, sans audit indépendant des performances."],["Essais en usine","Résultats de tâches chez Xiaomi en juillet 2026 et essais d'humanoïdes chez Zeekr. Un taux de réussite ne mesure pas la productivité de toute l'usine."],["Démonstrations","Les performances à la World Robot Conference illustrent des capacités dans des conditions précises, pas un emploi industriel durable."],["Capacités futures annoncées","Le communiqué UBTECH de novembre 2025 associe livraisons et objectifs de capacité. Capacité et commandes ne sont pas des heures de travail vérifiées."]],source:"Sources",table:"Tableau de données accessible",country:"Pays",value:"Robots pour 10 000 salariés"},
 es:{share:"China recibe la mayoría de los nuevos robots industriales",shareNote:"Proporción de las instalaciones mundiales de robots industriales en 2025. Son incorporaciones anuales, no el parque operativo.",china:"China",rest:"Resto del mundo",shareEnd:"China: 354.000 instalaciones. El 41 % restante se calcula restando a 100 % el 59 % redondeado de IFR.",density:"El mayor mercado no tiene la mayor densidad",densityNote:"Robots industriales por cada 10.000 trabajadores manufactureros, 2024. Los cinco países proceden de la misma publicación de IFR de abril de 2026.",countries:["Corea del Sur","Alemania","Japón","Estados Unidos","China"],densityEnd:"El denominador chino se revisó con nuevos datos de empleo. No deben empalmarse estos valores con las antiguas series chinas. Las barras parten de cero.",status:"Cuatro tipos de evidencia que conviene separar",statusNote:"Ejemplos seleccionados, revisados el 3 de octubre de 2026. No es un censo ni una clasificación de fabricantes.",rows:[["Producción operativa","BYD: automatización convencional observada en una fábrica de baterías. CATL: uso de Galbot S1 en líneas de producción declarado por la empresa, sin auditoría independiente de rendimiento."],["Pruebas en fábrica","Resultados de tareas de Xiaomi de julio de 2026 y pruebas de humanoides de Zeekr. La tasa de éxito de una tarea no mide la productividad de toda la planta."],["Demostraciones","Las actuaciones de la World Robot Conference muestran capacidades en condiciones concretas, no trabajo industrial sostenido."],["Capacidad futura anunciada","El comunicado de UBTECH de noviembre de 2025 combina entregas y objetivos de capacidad. Capacidad y pedidos no equivalen a horas de trabajo verificadas."]],source:"Fuentes",table:"Tabla de datos accesible",country:"País",value:"Robots por cada 10.000 trabajadores"},
 ar:{share:"الصين تستقبل معظم الروبوتات الصناعية الجديدة",shareNote:"حصة التركيبات العالمية للروبوتات الصناعية في 2025. هذه إضافات سنوية وليست إجمالي الوحدات العاملة.",china:"الصين",rest:"بقية العالم",shareEnd:"الصين: 354,000 تركيب. حُسبت حصة البقية البالغة 41% بطرح نسبة الاتحاد المقربة، 59%، من 100%.",density:"أكبر سوق لا يعني أعلى كثافة",densityNote:"روبوتات صناعية لكل 10,000 عامل في الصناعات التحويلية، 2024. الأرقام الخمسة من إصدار الاتحاد نفسه في أبريل 2026.",countries:["كوريا الجنوبية","ألمانيا","اليابان","الولايات المتحدة","الصين"],densityEnd:"عُدّل مقام النسبة الصينية باستخدام بيانات جديدة للقوى العاملة. لا تُدمج هذه القيم مع السلاسل الصينية القديمة. تبدأ الأعمدة من الصفر.",status:"أربعة أنواع من الأدلة يجب فصلها",statusNote:"أمثلة مختارة روجعت في 3 أكتوبر 2026. ليست تعداداً ولا ترتيباً للشركات.",rows:[["إنتاج قائم","BYD: أتمتة تقليدية رصدها تقرير ميداني في مصنع بطاريات. CATL: استخدام Galbot S1 على خطوط إنتاج بحسب الشركة، من دون تدقيق مستقل للأداء."],["تجارب داخل المصانع","نتائج مهام Xiaomi في يوليو 2026 وتجارب روبوتات بشرية الهيئة لدى Zeekr. نجاح مهمة لا يقيس إنتاجية المصنع كله."],["عروض تجريبية","استعراضات المؤتمر العالمي للروبوتات تظهر قدرات في ظروف محددة، ولا تثبت عملاً صناعياً مستمراً."],["طاقة إنتاجية مستقبلية معلنة","جمع بيان UBTECH في نوفمبر 2025 بين تسليمات وأهداف طاقة مستقبلية. الطاقة والطلبات ليست ساعات عمل متحققة."]],source:"المصادر",table:"جدول بيانات قابل للوصول",country:"الدولة",value:"روبوتات لكل 10,000 عامل"}
};
export function ChinaRoboticsGraphics({locale,kind}:{locale:Locale;kind:"share"|"density"|"status"}){
 const c=copy[locale],id=`china-robotics-${kind}`,values=[1220,449,446,307,166];
 const refs=kind==="share"?[s.market]:kind==="density"?[s.density]:[s.byd,s.catl,s.xiaomi,s.reuters,s.demo,s.ubtech];
 return <figure id={id} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={`${id}-title`} className="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
 <figcaption id={`${id}-title`} className="font-display text-xl font-bold sm:text-2xl">{c[kind]}</figcaption>
 <p className="mt-3 text-sm leading-relaxed text-white/75">{kind==="share"?c.shareNote:kind==="density"?c.densityNote:c.statusNote}</p>
 {kind==="share"&&<><div className="mt-6 flex h-10 overflow-hidden rounded" aria-hidden="true"><div className="bg-[#a92323]" style={{width:"59%"}}/><div className="bg-[#e9bd65]" style={{width:"41%"}}/></div><dl className="mt-4 grid grid-cols-2 gap-4"><div><dt>{c.china}</dt><dd className="text-3xl font-bold">59%</dd></div><div><dt>{c.rest}</dt><dd className="text-3xl font-bold text-[#e9bd65]">41%</dd></div></dl><p className="mt-4 text-sm text-white/75">{c.shareEnd}</p></>}
 {kind==="density"&&<><ol className="mt-6 space-y-4">{values.map((value,i)=><li key={value}><div className="mb-2 flex justify-between gap-3 text-sm"><span>{c.countries[i]}</span><b dir="ltr">{new Intl.NumberFormat(locale).format(value)}</b></div><div className="h-3 rounded bg-white/10" aria-hidden="true"><div className={`h-3 rounded ${i===4?"bg-[#cf3838]":"bg-[#e9bd65]"}`} style={{width:`${value/1220*100}%`}}/></div></li>)}</ol><p className="mt-5 text-sm leading-relaxed text-white/75">{c.densityEnd}</p><details className="mt-4"><summary className="cursor-pointer text-sm text-[#e9bd65]">{c.table}</summary><table className="mt-3 w-full text-start text-sm"><thead><tr><th className="p-2 text-start">{c.country}</th><th className="p-2 text-start">{c.value}</th></tr></thead><tbody>{values.map((v,i)=><tr key={v}><th scope="row" className="border-t border-white/20 p-2 text-start font-normal">{c.countries[i]}</th><td className="border-t border-white/20 p-2"><bdi>{new Intl.NumberFormat(locale).format(v)}</bdi></td></tr>)}</tbody></table></details></>}
 {kind==="status"&&<ol className="my-5 space-y-5">{c.rows.map(([title,text],i)=><li key={title} className="border-s-2 border-[#e9bd65] ps-4"><h3 className="font-bold text-[#e9bd65]">{i+1}. {title}</h3><p className="mt-2 text-sm leading-relaxed">{text}</p></li>)}</ol>}
 <p className="mt-5 text-xs text-white/70">{c.source}</p><ul className="mt-2 flex flex-wrap gap-x-4 gap-y-2 text-sm">{refs.map((r,i)=><li key={r.url}><a href={r.url} className="text-[#e9bd65] underline">{kind==="share"?"IFR · 2026 / 2025":kind==="density"?"IFR · 2026-04 / 2024":["BYD · 2026-09","CATL · 2026-06","Xiaomi · 2026","Reuters · 2026-08","AP · 2026-08","UBTECH · 2025-11"][i]}</a></li>)}</ul><p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
 </figure>;
}
