import type { Locale } from "@/lib/i18n/routing";
import { estoniaSources as s } from "@/data/estoniaArticle";

// Static editorial figures: React owns layout and percentage widths. No client runtime,
// hover-only evidence, remote data, persisted state or changes to the article template.
const dates=["1991","1996 / 1997","2000","2001","2002","2005","2008 / 2010","2014","2017","2024"];
const timelineRefs=[s.independence,s.tiger,s.story,s.story,s.story,s.elections,s.story,s.story,s.embassy,s.divorce];
export const estoniaVotingRows=[{year:2007,value:5.5},{year:2011,value:24.3},{year:2015,value:30.5},{year:2019,value:43.8},{year:2023,value:51.1}];
const copy={
 en:{timeline:"Building the digital state",timeNote:"Selected milestones. Spacing does not represent elapsed time.",events:["Independence restored","Tiger Leap announced; foundation established","e-Tax","National data-exchange layer","e-ID and digital signatures","First internet voting, local elections","Digital health records; digital prescriptions","e-Residency","Luxembourg data-hosting agreement","Online divorce application"],flow:"Three different jobs behind an online service",flowNote:"Simplified process, not a technical network diagram. Identity does not grant unlimited access.",steps:[["1. e-ID","The person authenticates to a service."],["2. Permission","The agency checks legal authority and access rights."],["3. X-tee / X-Road","Separate systems exchange authorised data through signed, encrypted, logged messages."]],vote:"Internet voting in parliamentary elections",voteNote:"Internet voters as a share of participating voters, not all eligible voters or residents. Published official percentages; 2023 is the latest parliamentary election in this series.",year:"Election year",share:"Internet voters (%)",table:"Accessible data table",source:"Sources",separate:"Other elections, shown separately: European Parliament 2024, 41.7%; local elections 2025, 45.8%. Different electorates and turnout prevent a like-for-like extension of this series."},
 fr:{timeline:"La construction de l’État numérique",timeNote:"Étapes choisies. L’espacement ne représente pas la durée.",events:["Indépendance rétablie","Tiger Leap annoncé ; création de la fondation","e-Tax","Couche nationale d’échange de données","Identité et signatures numériques","Premier vote par internet, élections locales","Dossiers médicaux numériques ; ordonnances numériques","e-Residency","Accord d’hébergement au Luxembourg","Demande de divorce en ligne"],flow:"Trois fonctions derrière un service en ligne",flowNote:"Parcours simplifié, sans représenter l’architecture technique. S’identifier ne donne pas un accès illimité.",steps:[["1. e-ID","La personne s’authentifie auprès du service."],["2. Autorisation","L’organisme vérifie le fondement légal et les droits d’accès."],["3. X-tee / X-Road","Des systèmes distincts échangent les données autorisées par des messages signés, chiffrés et journalisés."]],vote:"Le vote par internet aux élections législatives",voteNote:"Part des votants ayant utilisé internet, et non de tous les électeurs inscrits ou habitants. Pourcentages officiels publiés ; 2023 est le dernier scrutin législatif de cette série.",year:"Année du scrutin",share:"Votants par internet (%)",table:"Tableau de données accessible",source:"Sources",separate:"Autres scrutins, présentés séparément : européennes de 2024, 41,7 % ; locales de 2025, 45,8 %. Corps électoraux et participation différents empêchent de prolonger directement cette série."},
 es:{timeline:"La construcción del Estado digital",timeNote:"Hitos seleccionados. El espaciado no representa el tiempo transcurrido.",events:["Restauración de la independencia","Anuncio de Tiger Leap; creación de la fundación","e-Tax","Capa nacional de intercambio de datos","Identidad y firmas digitales","Primer voto por internet, elecciones locales","Historias clínicas digitales; recetas electrónicas","e-Residency","Acuerdo de alojamiento de datos en Luxemburgo","Solicitud de divorcio en línea"],flow:"Tres funciones detrás de un servicio digital",flowNote:"Proceso simplificado, no un diagrama técnico de red. Identificarse no concede acceso ilimitado.",steps:[["1. e-ID","La persona se autentica en el servicio."],["2. Autorización","El organismo comprueba la base legal y los permisos."],["3. X-tee / X-Road","Sistemas separados intercambian datos autorizados mediante mensajes firmados, cifrados y registrados."]],vote:"Voto por internet en elecciones parlamentarias",voteNote:"Usuarios del voto por internet como porcentaje de quienes participaron, no de todos los electores o residentes. Porcentajes oficiales; 2023 es la última elección parlamentaria de esta serie.",year:"Año electoral",share:"Votantes por internet (%)",table:"Tabla de datos accesible",source:"Fuentes",separate:"Otros comicios, por separado: Parlamento Europeo de 2024, 41,7 %; locales de 2025, 45,8 %. Los distintos electorados y la participación impiden prolongar directamente esta serie."},
 ar:{timeline:"بناء الدولة الرقمية",timeNote:"محطات مختارة. المسافات لا تمثل المدد الزمنية.",events:["استعادة الاستقلال","إعلان قفزة النمر ثم إنشاء مؤسستها","الضرائب الإلكترونية","طبقة وطنية لتبادل البيانات","الهوية والتوقيعات الرقمية","أول تصويت عبر الإنترنت في الانتخابات المحلية","السجلات الصحية الرقمية ثم الوصفات الإلكترونية","الإقامة الإلكترونية","اتفاق استضافة البيانات في لوكسمبورغ","طلب الطلاق عبر الإنترنت"],flow:"ثلاث وظائف وراء الخدمة الإلكترونية",flowNote:"مسار مبسط وليس مخططا تقنيا للشبكة. إثبات الهوية لا يمنح وصولا غير محدود.",steps:[["1. الهوية الرقمية","يثبت الشخص هويته للدخول إلى الخدمة."],["2. الصلاحية","تتحقق الجهة من الأساس القانوني وحقوق الوصول."],["3. X-tee / X-Road","تتبادل أنظمة منفصلة البيانات المسموح بها عبر رسائل موقعة ومشفرة ومسجلة."]],vote:"التصويت عبر الإنترنت في الانتخابات البرلمانية",voteNote:"نسبة مستخدمي التصويت عبر الإنترنت من المشاركين، وليست من جميع المؤهلين أو السكان. نسب منشورة رسميا، و2023 أحدث انتخابات برلمانية في هذه السلسلة.",year:"سنة الانتخاب",share:"المصوتون عبر الإنترنت (%)",table:"جدول بيانات متاح للجميع",source:"المصادر",separate:"انتخابات أخرى تعرض منفصلة: البرلمان الأوروبي في 2024 بنسبة 41.7%، والانتخابات المحلية في 2025 بنسبة 45.8%. اختلاف الناخبين والمشاركة يمنع إلحاقها مباشرة بالسلسلة."}
};
export function EstoniaGraphics({locale,kind}:{locale:Locale;kind:"timeline"|"flow"|"voting"}){
 const c=copy[locale];const id=`estonia-${kind}`;const format=(n:number)=>new Intl.NumberFormat(locale,{maximumFractionDigits:1}).format(n);
 const refs=kind==="timeline"?[s.tiger,s.story,s.embassy,s.divorce]:kind==="flow"?[s.identity,s.exchange]:[s.elections];
 return <figure id={id} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={`${id}-title`} className="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
 <figcaption id={`${id}-title`} className="font-display text-xl font-bold sm:text-2xl">{kind==="timeline"?c.timeline:kind==="flow"?c.flow:c.vote}</figcaption>
 <p className="mt-3 text-sm leading-relaxed text-white/75">{kind==="timeline"?c.timeNote:kind==="flow"?c.flowNote:c.voteNote}</p>
 {kind==="timeline"?<ol className="my-5 grid gap-4 sm:grid-cols-2">{dates.map((date,i)=><li key={date} className="border-s-2 border-[#e9bd65] ps-4"><p className="font-bold text-[#e9bd65]"><bdi>{date}</bdi></p><p className="mt-1 text-sm leading-relaxed">{c.events[i]} <a href={timelineRefs[i].url} aria-label={`${c.source}: ${date}`} className="text-[#e9bd65] underline">[{i+1}]</a></p></li>)}</ol>:kind==="flow"?<ol className="my-5 space-y-4">{c.steps.map(([title,text])=><li key={title} className="border-s-4 border-[#e9bd65] ps-4"><h3 className="text-base font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed">{text}</p></li>)}</ol>:<>
 <div className="my-6 space-y-5" aria-hidden="true">{estoniaVotingRows.map(r=><div key={r.year}><div className="mb-2 flex justify-between text-sm"><bdi>{r.year}</bdi><strong>{format(r.value)}%</strong></div><div className="h-3 bg-white/10"><div className="h-3 bg-[#e9bd65]" style={{width:`${r.value}%`}} /></div></div>)}<div className="flex justify-between text-xs text-white/65"><span>0%</span><span>100%</span></div></div>
 <details className="rounded-lg border border-white/20 p-3"><summary className="cursor-pointer text-sm font-semibold text-[#e9bd65]">{c.table}</summary><table className="mt-4 w-full text-start text-sm"><caption className="sr-only">{c.vote}</caption><thead><tr><th scope="col" className="py-2 text-start">{c.year}</th><th scope="col" className="py-2 text-end">{c.share}</th></tr></thead><tbody>{estoniaVotingRows.map(r=><tr key={r.year} className="border-t border-white/10"><th scope="row" className="py-2 text-start"><bdi>{r.year}</bdi></th><td className="py-2 text-end">{format(r.value)}%</td></tr>)}</tbody></table></details>
 <p className="mt-4 text-sm leading-relaxed text-white/75">{c.separate}</p></>}
 <p className="mt-5 text-xs text-white/70">{c.source}</p><ul className="mt-2 flex flex-wrap gap-x-4 gap-y-2 text-sm">{refs.map((r,i)=><li key={r.url}><a href={r.url} className="text-[#e9bd65] underline">{kind==="timeline"?["Harno","e-Estonia","Luxembourg","Tallinn"][i]:kind==="flow"?["RIA: e-ID","RIA: X-tee"][i]:"Valimised.ee"}</a></li>)}</ul><p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
 </figure>;
}
