import type { Locale } from "@/lib/i18n/routing";

const copy = {
 en: { titles:["DNA identity: the denominator matters","Our great ape family","How human chromosome 2 formed","Different timescales, different questions"], notes:["Selected published comparisons, not a ranking of whole-genome identity. The two 2005 figures use different treatments of gaps; the 2012 figures use single-copy autosomal regions.","Schematic species relationships. Branch lengths do not represent time. Orangutans and gorillas include multiple living species; all tips represent living lineages.","Conceptual diagram, not to scale. Two ancestral chromosomes fused; this is not a depiction of modern chimpanzee chromosomes physically becoming human.","Selected milestones, not equal-duration intervals. Divergence estimates are approximate; fossil dating has its own uncertainty."], rows:[ ["Human / chimpanzee|Almost 99%: directly comparable DNA, NHGRI 2005","Human / chimpanzee|96%: historical calculation including insertions and deletions, NHGRI 2005","Human / bonobo|98.7%: corresponding single-copy autosomal regions, Nature 2012","Chimpanzee / bonobo|99.6%: the same region category, Nature 2012"], ["Orangutans|Earlier-diverging great ape branch","Gorillas|Branch before the human–Pan common ancestor","Humans|Sister lineage to Pan","Chimpanzees + bonobos|Two species of Pan; equally close living relatives of humans"], ["Two ancestral chromosomes|Each originally had ends and a centromere","Internal fusion junction|Opposing remnants of telomeric repeats","Human chromosome 2|One active centromere and an inactivated ancestral centromere"], ["About 8–6 million years ago|Human and Pan ancestral lineages diverge","About 2 million years ago|Chimpanzee and bonobo lineages diverge: 2012 genomic estimate","315,000 ±34,000 years ago|Heated flints associated with Jebel Irhoud early Homo sapiens fossils","2005 → 2025|Draft chimpanzee comparison to complete ape genome assemblies"] ],a:"Ancestral A",b:"Ancestral B",human:"Human chromosome 2",junction:"Fusion",active:"Active centromere",inactive:"Inactivated centromere",source:"Sources" },
 fr: { titles:["Identité de l’ADN : le dénominateur compte","Notre famille de grands singes","La formation du chromosome humain 2","Des échelles de temps différentes"],notes:["Comparaisons publiées choisies, pas classement de génomes entiers. Les chiffres de 2005 traitent différemment les lacunes ; ceux de 2012 concernent des régions autosomiques à copie unique.","Relations schématiques entre espèces. La longueur des branches ne mesure pas le temps. Orangs-outans et gorilles comprennent plusieurs espèces ; les extrémités représentent des lignées actuelles.","Schéma conceptuel sans échelle. Deux chromosomes ancestraux ont fusionné ; ce ne sont pas des chromosomes de chimpanzés actuels se transformant en chromosomes humains.","Repères choisis, sans intervalles de durée égale. Les divergences sont estimées ; les datations fossiles ont leur propre incertitude."],rows:[ ["Humain / chimpanzé|Près de 99 % : ADN directement comparable, NHGRI 2005","Humain / chimpanzé|96 % : calcul historique avec insertions et délétions, NHGRI 2005","Humain / bonobo|98,7 % : régions autosomiques correspondantes à copie unique, Nature 2012","Chimpanzé / bonobo|99,6 % : même catégorie de régions, Nature 2012"],["Orangs-outans|Branche séparée plus tôt","Gorilles|Branche antérieure à l’ancêtre commun humain–Pan","Humains|Lignée sœur de Pan","Chimpanzés + bonobos|Deux espèces de Pan, également proches de l’humain"],["Deux chromosomes ancestraux|Chacun possédait des extrémités et un centromère","Jonction interne|Vestiges opposés de répétitions télomériques","Chromosome humain 2|Un centromère actif et un centromère ancestral inactivé"],["Il y a environ 8–6 millions d’années|Divergence des lignées ancestrales humaine et Pan","Il y a environ 2 millions d’années|Divergence chimpanzé–bonobo : estimation génomique de 2012","Il y a 315 000 ±34 000 ans|Silex chauffés associés aux fossiles de Jebel Irhoud","2005 → 2025|Du premier génome de chimpanzé aux assemblages complets de singes"]],a:"Ancêtre A",b:"Ancêtre B",human:"Chromosome humain 2",junction:"Fusion",active:"Centromère actif",inactive:"Centromère inactivé",source:"Sources" },
 ar: { titles:["تطابق الحمض النووي: المقام مهم","عائلتنا من القردة العليا","كيف تشكل الكروموسوم البشري 2","أزمنة مختلفة وأسئلة مختلفة"],notes:["مقارنات منشورة مختارة، وليست ترتيباً لتطابق الجينوم الكامل. يختلف حساب الفجوات في قيمتي 2005؛ وتخص قيمتا 2012 مناطق جسمية أحادية النسخة.","علاقات أنواع تخطيطية؛ لا تمثل أطوال الفروع الزمن. تشمل الغوريلا وإنسان الغاب أنواعاً حية متعددة، وتمثل الأطراف سلالات حية.","رسم تصوري غير مرسوم بمقياس. اندمج كروموسومان سلفيان؛ لا يصور كروموسومات شمبانزي معاصر تتحول فعلياً إلى كروموسوم بشري.","محطات مختارة بفواصل غير متساوية زمنياً. أزمنة الانفصال تقديرية، ولتأريخ الأحافير هامش عدم يقين خاص."],rows:[["الإنسان / الشمبانزي|قرابة 99%: حمض نووي قابل للمقارنة مباشرة، NHGRI 2005","الإنسان / الشمبانزي|96%: حساب تاريخي يشمل الإدخالات والحذوفات، NHGRI 2005","الإنسان / البونوبو|98.7%: مناطق جسمية متناظرة أحادية النسخة، Nature 2012","الشمبانزي / البونوبو|99.6%: الفئة نفسها من المناطق، Nature 2012"],["إنسان الغاب|فرع انفصل أقدم","الغوريلا|فرع قبل سلف الإنسان وPan المشترك","البشر|السلالة الشقيقة لـ Pan","الشمبانزي والبونوبو|نوعا Pan وأقرب الأقرباء الأحياء بالتساوي"],["كروموسومان سلفيان|لكل منهما نهايتان وسنترومير","وصلة اندماج داخلية|بقايا متعاكسة لتكرارات تيلوميرية","الكروموسوم البشري 2|سنترومير نشط وآخر سلفي معطل"],["قبل نحو 8–6 ملايين سنة|انفصال السلالتين السلفيتين للبشر وPan","قبل نحو مليوني سنة|انفصال الشمبانزي والبونوبو وفق تقدير جينومي عام 2012","قبل 315 ألف سنة ±34 ألف سنة|صوان محروق مرتبط بأحافير جبل إيغود","2005 ← 2025|من مقارنة أولية للشمبانزي إلى تجميعات كاملة لجينومات القردة"]],a:"السلف A",b:"السلف B",human:"الكروموسوم البشري 2",junction:"اندماج",active:"سنترومير نشط",inactive:"سنترومير معطل",source:"المصادر" },
 es: { titles:["Identidad del ADN: importa el denominador","Nuestra familia de grandes simios","Cómo se formó el cromosoma humano 2","Escalas temporales distintas"],notes:["Comparaciones publicadas seleccionadas, no clasificación de genomas enteros. Las cifras de 2005 tratan los huecos de forma distinta; las de 2012 usan regiones autosómicas de copia única.","Relaciones esquemáticas entre especies. La longitud de las ramas no mide tiempo. Gorilas y orangutanes incluyen varias especies; todos los extremos son linajes vivos.","Diagrama conceptual sin escala. Se fusionaron dos cromosomas ancestrales; no muestra cromosomas de chimpancés actuales convirtiéndose físicamente en humanos.","Hitos seleccionados, sin intervalos de igual duración. Las divergencias son estimaciones; la datación fósil tiene su propia incertidumbre."],rows:[["Humano / chimpancé|Casi 99 %: ADN directamente comparable, NHGRI 2005","Humano / chimpancé|96 %: cálculo histórico con inserciones y deleciones, NHGRI 2005","Humano / bonobo|98,7 %: regiones autosómicas correspondientes de copia única, Nature 2012","Chimpancé / bonobo|99,6 %: la misma categoría de regiones, Nature 2012"],["Orangutanes|Rama que divergió antes","Gorilas|Rama anterior al antepasado común humano–Pan","Humanos|Linaje hermano de Pan","Chimpancés + bonobos|Dos especies de Pan, parientes igualmente cercanos"],["Dos cromosomas ancestrales|Cada uno tenía extremos y un centrómero","Unión interna|Restos opuestos de repeticiones teloméricas","Cromosoma humano 2|Un centrómero activo y otro ancestral inactivado"],["Hace unos 8–6 millones de años|Divergencia de los linajes ancestrales humano y Pan","Hace unos 2 millones de años|Separación chimpancé–bonobo: estimación genómica de 2012","Hace 315.000 ±34.000 años|Sílex calentados asociados a los fósiles de Jebel Irhoud","2005 → 2025|Del borrador de chimpancé a ensamblajes completos de simios"]],a:"Ancestral A",b:"Ancestral B",human:"Cromosoma humano 2",junction:"Fusión",active:"Centrómero activo",inactive:"Centrómero inactivado",source:"Fuentes" }
};
const refs=[[["NHGRI 2005","https://www.genome.gov/15515096/2005-release-new-genome-comparison-finds-chimps-humans-very-similar-at-dna-level"],["Nature 2012, single-copy autosomal comparison","https://www.nature.com/articles/nature11128"]],[["Smithsonian, Genetics","https://humanorigins.si.edu/evidence/genetics"],["Nature 2012, gorilla genome","https://www.nature.com/articles/nature10842"]],[["PNAS 1991, fusion junction","https://doi.org/10.1073/pnas.88.20.9051"],["Genome Research 2002, fusion structure","https://genome.cshlp.org/content/12/11/1651.full.pdf"]],[["Smithsonian","https://humanorigins.si.edu/evidence/genetics"],["Nature 2012","https://www.nature.com/articles/nature11128"],["Nature 2017, fossil dating","https://www.nature.com/articles/nature22335"],["Nature 2025","https://www.nature.com/articles/s41586-025-08816-3"]]];
export function HumanApeDnaGraphics({locale,kind}:{locale:Locale;kind:"similarity"|"tree"|"fusion"|"timeline"}) {
 const n={similarity:0,tree:1,fusion:2,timeline:3}[kind],c=copy[locale],id=`ape-dna-${kind}`;
 return <figure id={id} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={id+"-title"} className="flow-root my-10 scroll-mt-28 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
 <figcaption id={id+"-title"} className="font-display text-xl font-bold sm:text-2xl">{c.titles[n]}</figcaption>
 <p className="mt-3 text-sm leading-relaxed text-white/75">{c.notes[n]}</p>
 {kind==="tree"&&<svg viewBox="0 0 620 290" role="img" aria-labelledby={id+"-title"} aria-describedby={id+"-data"} className="mx-auto mt-5 w-full max-w-2xl" style={{direction:"ltr"}}>
 <path d="M20 30H80V250M80 30H280M80 250H135V95M135 95H280M135 250H190V155M190 155H280M190 250H245V215M245 215H280M245 250H280" fill="none" stroke="#e9bd65" strokeWidth="3"/>
 {[c.rows[1][0].split('|')[0],c.rows[1][1].split('|')[0],c.rows[1][2].split('|')[0],locale==="ar"?"الشمبانزي":locale==="fr"?"Chimpanzés":locale==="es"?"Chimpancés":"Chimpanzees",locale==="ar"?"البونوبو":"Bonobos"].map((t,i)=><text key={t} x="300" y={[36,101,161,221,256][i]} fill="white" fontSize="20">{t}</text>)}
 </svg>}
 {kind==="fusion"&&<svg viewBox="0 0 650 330" role="img" aria-labelledby={id+"-title"} aria-describedby={id+"-data"} className="mx-auto mt-5 w-full max-w-2xl" style={{direction:"ltr"}}>
 <rect x="40" y="55" width="230" height="24" rx="12" fill="#e9bd65"/><rect x="350" y="55" width="230" height="24" rx="12" fill="#e9bd65"/>
 <circle cx="140" cy="67" r="12" fill="#FF1A1A"/><circle cx="440" cy="67" r="12" fill="#FF1A1A"/>
 <text x="40" y="38" fill="white" fontSize="19">{c.a}</text><text x="350" y="38" fill="white" fontSize="19">{c.b}</text>
 <path d="M270 90L305 140M350 90L325 140" stroke="white" strokeWidth="2" fill="none"/>
 <rect x="40" y="160" width="540" height="24" rx="12" fill="#e9bd65"/><circle cx="140" cy="172" r="12" fill="#FF1A1A"/><circle cx="440" cy="172" r="12" fill="#101010" stroke="#FF1A1A" strokeWidth="3"/>
 <path d="M310 150V197" stroke="white" strokeWidth="3"/>
 <text x="310" y="225" textAnchor="middle" fill="white" fontSize="19">{c.junction}</text>
 <text x="140" y="268" textAnchor="middle" fill="white" fontSize="17">{c.active}</text><text x="450" y="295" textAnchor="middle" fill="white" fontSize="17">{c.inactive}</text>
 </svg>}
 <ol id={id+"-data"} className="mt-6 space-y-5 border-s-2 border-[#e9bd65]/60 ps-5">{c.rows[n].map((r,i)=>{const [label,detail]=r.split('|');return <li key={i}><h3 className="font-display text-lg font-bold text-[#e9bd65]">{label}</h3><p className="mt-2 text-sm leading-relaxed text-white/85">{detail}</p></li>})}</ol>
 <p className="mt-5 text-xs leading-relaxed">{c.source}: {refs[n].map(([label,url],i)=><span key={url}>{i>0&&"; "}<a href={url} className="text-[#e9bd65] underline">{label}</a></span>)}</p>
 <p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
 </figure>;
}
