import type { Locale } from "@/lib/i18n/routing";

const copy = {
  en: { timeline: "From villages to cities, then regional change", note: "Approximate dates. Regional sequences differ. This is an ordered chronology, not a scale of equal durations.", dates: ["c. 7000 BCE", "c. 3300–2600 BCE", "c. 2600–1900 BCE", "c. 1900–1300 BCE"], stages: ["Farming precursors", "Early Harappan", "Mature Harappan", "Late Harappan"], details: ["Mehrgarh belongs to the earlier farming background, not the mature civilization.", "Regional settlements develop; Harappa’s early sequence begins around 3300 BCE.", "Large urban centres and shared material practices connect the region.", "Urban contraction and changing regional traditions; populations continue."], cities: "Four major cities, four settings", cityNote: "Selected centres, not every major settlement. Modern locations orient the reader; they are not ancient political boundaries.", locations: ["Punjab, Pakistan", "Sindh, Pakistan", "Kutch, Gujarat, India", "Haryana, India"], features: ["Long excavation sequence, crafts and inscribed objects", "Brick neighbourhoods, wells, drains and Great Bath", "Stone construction and seasonal-water reservoirs", "Urban settlement, burials and ancient-DNA research"], source: "Sources and dating", citySource: "Archaeological sources" },
  fr: { timeline: "Des villages aux villes, puis aux transformations régionales", note: "Dates approximatives et séquences régionales variables. Chronologie ordonnée, sans échelle de durées égales.", dates: ["v. 7000 av. n. è.", "v. 3300–2600 av. n. è.", "v. 2600–1900 av. n. è.", "v. 1900–1300 av. n. è."], stages: ["Précurseurs agricoles", "Phase ancienne", "Phase mature", "Phase tardive"], details: ["Mehrgarh appartient au contexte agricole antérieur, pas à la civilisation mature.", "Développement des établissements régionaux ; séquence de Harappa vers 3300.", "Grands centres urbains et pratiques matérielles communes relient la région.", "Recul urbain et nouvelles traditions régionales ; les populations continuent."], cities: "Quatre grandes villes, quatre milieux", cityNote: "Centres sélectionnés, non une liste exhaustive. Les lieux actuels servent de repères, pas de frontières anciennes.", locations: ["Pendjab, Pakistan", "Sindh, Pakistan", "Kutch, Gujarat, Inde", "Haryana, Inde"], features: ["Longue séquence de fouilles, artisanat et objets inscrits", "Quartiers de briques, puits, drains et Grand Bain", "Construction en pierre et réservoirs d’eau saisonnière", "Établissement urbain, sépultures et recherche génétique"], source: "Sources et datation", citySource: "Sources archéologiques" },
  es: { timeline: "De las aldeas a las ciudades y al cambio regional", note: "Fechas aproximadas; las secuencias regionales varían. Cronología ordenada, sin escala de duraciones iguales.", dates: ["c. 7000 a. C.", "c. 3300–2600 a. C.", "c. 2600–1900 a. C.", "c. 1900–1300 a. C."], stages: ["Antecedentes agrícolas", "Fase temprana", "Fase madura", "Fase tardía"], details: ["Mehrgarh es un antecedente agrícola, no la civilización madura.", "Crecen asentamientos regionales; Harappa tiene una secuencia desde aproximadamente 3300.", "Grandes centros urbanos y prácticas compartidas conectan la región.", "Contracción urbana y nuevas tradiciones regionales; la población continúa."], cities: "Cuatro grandes ciudades, cuatro entornos", cityNote: "Centros seleccionados, no una lista completa. Las ubicaciones actuales orientan, sin representar fronteras antiguas.", locations: ["Punjab, Pakistán", "Sindh, Pakistán", "Kutch, Gujarat, India", "Haryana, India"], features: ["Larga secuencia de excavación, artesanía y objetos inscritos", "Barrios de ladrillo, pozos, desagües y Gran Baño", "Construcción en piedra y depósitos de agua estacional", "Asentamiento urbano, enterramientos y ADN antiguo"], source: "Fuentes y datación", citySource: "Fuentes arqueológicas" },
  ar: { timeline: "من القرى إلى المدن ثم التحول الإقليمي", note: "تواريخ تقريبية تختلف تسلسلاتها محليا. ترتيب زمني مقروء، وليس مقياسا لفترات متساوية.", dates: ["نحو 7000 ق.م.", "نحو 3300–2600 ق.م.", "نحو 2600–1900 ق.م.", "نحو 1900–1300 ق.م."], stages: ["مجتمعات زراعية سابقة", "هارابا المبكرة", "هارابا الناضجة", "هارابا المتأخرة"], details: ["مهرغاره من الخلفية الزراعية الأقدم، وليست الحضارة الناضجة.", "تنمو المستوطنات المحلية؛ يبدأ تسلسل هارابا نحو 3300 قبل الميلاد.", "تربط المراكز الحضرية الكبرى والممارسات المشتركة المنطقة.", "تراجع حضري وتغير التقاليد المحلية مع استمرار السكان."], cities: "أربع مدن كبرى في أربع بيئات", cityNote: "مراكز مختارة، لا جميع المستوطنات المهمة. المواقع الحديثة للشرح وليست حدودا سياسية قديمة.", locations: ["البنجاب، باكستان", "السند، باكستان", "كوتش، غوجارات، الهند", "هاريانا، الهند"], features: ["تسلسل حفريات طويل وصناعة وقطع منقوشة", "أحياء من الطوب وآبار ومصارف والحمام الكبير", "بناء حجري وخزانات للجريان الموسمي", "استيطان حضري ومدافن وبحث في الحمض النووي القديم"], source: "المصادر والتأريخ", citySource: "المصادر الأثرية" }
};

const names = {en:["Harappa","Mohenjo-daro","Dholavira","Rakhigarhi"],fr:["Harappa","Mohenjo-daro","Dholavira","Rakhigarhi"],es:["Harappa","Mohenjo-daro","Dholavira","Rakhigarhi"],ar:["هارابا","موهينجو دارو","دولافيرا","راخيغارهي"]};
const citySources = ["https://www.harappa.com/content/recent-indus-discoveries-and-highlights-excavations-harappa-1998-2000", "https://whc.unesco.org/en/list/138/", "https://whc.unesco.org/en/list/1645/", "https://reich.hms.harvard.edu/sites/reich.hms.harvard.edu/files/inline-files/2019_Cell_ShindeNarasimhan_Rakhigarhi.pdf"];

export function IndusValleyGraphics({locale,kind}:{locale:Locale;kind:"timeline"|"cities"}) {
  const c=copy[locale],timeline=kind==="timeline",id=`indus-${kind}`;
  return <figure id={id} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={`${id}-title`} className="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
    <figcaption id={`${id}-title`} className="font-display text-xl font-bold sm:text-2xl">{timeline?c.timeline:c.cities}</figcaption>
    <p className="mt-3 text-sm leading-relaxed text-white/75">{timeline?c.note:c.cityNote}</p>
    {timeline ? <ol className="mt-6 space-y-5 border-s-2 border-[#e9bd65]/60 ps-5">{c.stages.map((stage,i)=><li key={stage}>
      <p className="text-sm font-bold text-[#e9bd65]">{c.dates[i]}</p><h3 className="mt-1 font-display text-lg font-bold">{stage}</h3><p className="mt-1 text-sm leading-relaxed text-white/80">{c.details[i]}</p>
    </li>)}</ol> : <div className="mt-6 grid gap-4 sm:grid-cols-2">{names[locale].map((name,i)=><div key={name} className="border-s-2 border-[#FF1A1A] ps-4"><h3 className="font-display text-lg font-bold">{name}</h3><p className="mt-1 text-sm text-[#e9bd65]">{c.locations[i]}</p><p className="mt-2 text-sm leading-relaxed text-white/80">{c.features[i]}</p><a href={citySources[i]} className="mt-2 inline-block text-xs text-[#e9bd65] underline">{c.citySource}</a></div>)}</div>}
    {timeline && <p className="mt-5 text-xs leading-relaxed">{c.source}: <a className="text-[#e9bd65] underline" href="https://www.harappa.com/content/reconstructing-history-harappan-civilization">Harappa</a>, <a className="text-[#e9bd65] underline" href={citySources[0]}>Kenoyer &amp; Meadow</a></p>}
    <p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
  </figure>;
}
