type Locale = "en" | "fr" | "ar" | "es";
const award="https://www.nasa.gov/news-release/nasa-awards-contract-to-develop-5g-communications-for-moon/";
const study="https://www.nasa.gov/wp-content/uploads/2026/02/lunar-3gpp-gem-paper-rev3-1.pdf";
const previous="https://www.nokia.com/newsroom/nokia-and-intuitive-machines-deliver-first-cellular-network-to-the-moon-achieve-some-key-mission-objectives/";
const delay="https://science.nasa.gov/wp-content/uploads/2023/05/188_fed0ad8278e728107533d509b24dc68b_SmithsimmonsDrew.pdf";
const copy={
en:{timeline:"From tests to a planned lunar demonstration",note:"Chronological milestones and contract work periods, not confirmed launch dates. No permanent 5G service is established by these events.",events:["March 2025: 4G hardware powered on during IM-2; intended cellular call not completed","September 30, 2026: NASA announces approximately $38 million award","October 1, 2026 to January 31, 2028: network-in-a-box development and laboratory work period","November 30, 2026 to December 31, 2028: integrated lunar network and flight demonstration work period"],network:"Two layers of lunar communication",concept:"Simplified research concept, not the awarded system’s final design. Local links exchange data in both directions; the Earth connection is a separate layer.",nodes:["Astronaut suit radios","Rover terminals","Science instruments"],local:"Local 5G + Wi-Fi 6",hub:"Surface network equipment",backhaul:"Separate space communications link",earth:"Earth mission operations",latency:"About 1.3 seconds one way to Earth; roughly 2.6 seconds round trip before other delays. Faster local radios cannot remove light-time.",source:"Sources"},
fr:{timeline:"Des essais à une démonstration lunaire prévue",note:"Étapes et périodes contractuelles, pas des dates de lancement confirmées. Elles ne prouvent pas un service 5G permanent.",events:["Mars 2025 : matériel 4G activé lors d’IM-2, sans appel cellulaire réalisé","30 septembre 2026 : annonce du contrat d’environ 38 millions de dollars","1er octobre 2026 au 31 janvier 2028 : développement du réseau compact et travaux de laboratoire","30 novembre 2026 au 31 décembre 2028 : période du réseau intégré et de la démonstration lunaire"],network:"Deux niveaux de communication lunaire",concept:"Concept de recherche simplifié, pas le plan final du système commandé. Les échanges locaux sont bidirectionnels ; la liaison terrestre constitue un autre niveau.",nodes:["Radios des combinaisons","Terminaux des rovers","Instruments scientifiques"],local:"5G locale + Wi-Fi 6",hub:"Équipement du réseau de surface",backhaul:"Liaison spatiale distincte",earth:"Opérations terrestres",latency:"Environ 1,3 seconde dans un sens ; 2,6 secondes aller-retour avant les autres délais. Une radio plus rapide ne supprime pas le temps de trajet de la lumière.",source:"Sources"},
es:{timeline:"De los ensayos a una demostración lunar prevista",note:"Hitos y períodos contractuales, no fechas de lanzamiento confirmadas. No acreditan un servicio permanente 5G.",events:["Marzo de 2025: equipos 4G encendidos en IM-2; llamada celular no completada","30 de septiembre de 2026: anuncio del contrato de unos 38 millones de dólares","1 de octubre de 2026 al 31 de enero de 2028: desarrollo de la red compacta y trabajo de laboratorio","30 de noviembre de 2026 al 31 de diciembre de 2028: período de red integrada y demostración lunar"],network:"Dos capas de comunicación lunar",concept:"Concepto simplificado de investigación, no el diseño final contratado. Los enlaces locales son bidireccionales; la conexión terrestre es otra capa.",nodes:["Radios de los trajes","Terminales de rovers","Instrumentos científicos"],local:"5G local + Wi-Fi 6",hub:"Equipos de la red superficial",backhaul:"Enlace espacial separado",earth:"Operaciones en la Tierra",latency:"Unos 1,3 segundos en un sentido; 2,6 segundos de ida y vuelta antes de otros retardos. Las radios locales no eliminan el tiempo de viaje de la luz.",source:"Fuentes"},
ar:{timeline:"من التجارب إلى تجربة قمرية مخططة",note:"محطات مرتبة وفترات تعاقدية، وليست مواعيد إطلاق مؤكدة أو إثباتا لخدمة دائمة من الجيل الخامس.",events:["مارس 2025: تشغيل معدات الجيل الرابع في IM-2 دون إنجاز الاتصال الخلوي المقصود","30 سبتمبر 2026: إعلان عقد بنحو 38 مليون دولار","1 أكتوبر 2026 إلى 31 يناير 2028: تطوير الشبكة المدمجة وأعمال المختبر","30 نوفمبر 2026 إلى 31 ديسمبر 2028: فترة الشبكة المتكاملة والتجربة القمرية"],network:"طبقتان للاتصال القمري",concept:"تصور بحثي مبسط وليس التصميم النهائي للعقد. الاتصالات المحلية ثنائية الاتجاه، والوصلة الأرضية طبقة مستقلة.",nodes:["أجهزة بدلات الرواد","أجهزة المركبات الجوالة","المعدات العلمية"],local:"جيل خامس محلي وواي فاي 6",hub:"معدات الشبكة السطحية",backhaul:"وصلة فضائية مستقلة",earth:"عمليات المهمة على الأرض",latency:"نحو 1.3 ثانية في اتجاه واحد، و2.6 ثانية للذهاب والعودة قبل أي تأخر إضافي. لا تلغي الأجهزة المحلية زمن انتقال الضوء.",source:"المصادر"}
};
export function Lunar5gGraphics({locale,kind}:{locale:Locale;kind:"timeline"|"network"}) {
 const c=copy[locale],id=`lunar-${kind}`,timeline=kind==="timeline";
 return <figure id={id} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={`${id}-title`} className="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
  <figcaption id={`${id}-title`} className="font-display text-xl font-bold sm:text-2xl">{timeline?c.timeline:c.network}</figcaption>
  <p className="mt-3 text-sm leading-relaxed text-white/75">{timeline?c.note:c.concept}</p>
  {timeline?<ol className="mt-6 space-y-5 border-s-2 border-[#e9bd65]/60 ps-5">{c.events.map((event,i)=><li key={event} className="text-sm leading-relaxed"><span className="mb-1 block font-bold text-[#e9bd65]" aria-hidden="true">{i+1}</span>{event}</li>)}</ol>:<div className="mt-6 space-y-3 text-center text-sm">
   <ul className="grid gap-2 sm:grid-cols-3">{c.nodes.map(n=><li key={n} className="rounded-lg border border-white/25 p-3">{n}</li>)}</ul>
   <p className="text-[#e9bd65]">↕ {c.local}</p>
   <p className="rounded-lg border border-[#e9bd65]/60 bg-[#e9bd65]/10 p-4 font-semibold">{c.hub}</p>
   <p className="text-[#ff6060]">↕ {c.backhaul}</p>
   <p className="rounded-lg border border-white/25 p-4 font-semibold">{c.earth}</p>
   <p className="pt-3 text-start text-xs leading-relaxed text-white/75">{c.latency}</p>
  </div>}
  <p className="mt-5 flex flex-wrap gap-2 text-xs">{c.source}: <a className="text-[#e9bd65] underline" href={timeline?award:study}>NASA {timeline?"2026":"GEM"}</a><span>·</span><a className="text-[#e9bd65] underline" href={timeline?previous:delay}>{timeline?"Nokia IM-2":"NASA"}</a></p>
  <p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
 </figure>;
}
