import type { Locale } from "@/lib/i18n/routing";
import { messiSources as s } from "@/data/messiFarewellArticle";
const copy={
 en:{timeline:"Argentina: the long road to a farewell",note:"Selected events. Equal spacing does not represent elapsed time. October 6 is scheduled, not completed.",rows:["Youth world title and senior debut","Olympic gold, a separate age-regulated competition","World Cup runner-up","Retirement announcement, then a return","First senior Copa América title","Finalissima and World Cup champion","Second Copa América title","Third World Cup final; retirement announced August 31","Planned Benin farewell and UBA honorary presentation"],goals:"Six World Cups, 21 goals",unit:"Goals in each edition",caption:"Tournament totals, not goals per match. Shootout kicks are excluded. The 2026 format offered more matches than earlier editions.",source:"Sources"},
 fr:{timeline:"Argentine : le long chemin vers les adieux",note:"Étapes choisies. Les espacements ne représentent pas les durées. Le 6 octobre est prévu, pas encore accompli.",rows:["Titre mondial juniors et débuts seniors","Or olympique, compétition soumise à des règles d’âge","Finaliste de la Coupe du monde","Annonce de retraite, puis retour","Premier titre senior en Copa América","Vainqueur de la Finalissima et champion du monde","Deuxième Copa América","Troisième finale mondiale ; retraite annoncée le 31 août","Adieux prévus contre le Bénin et remise du titre de l’UBA"],goals:"Six Coupes du monde, 21 buts",unit:"Buts par édition",caption:"Totaux par tournoi, pas buts par match. Tirs au but exclus. Le format 2026 offrait davantage de rencontres que les précédents.",source:"Sources"},
 es:{timeline:"Argentina: el largo camino a la despedida",note:"Hitos seleccionados. Las distancias no representan el tiempo transcurrido. El 6 de octubre es una fecha prevista, no cumplida.",rows:["Título mundial juvenil y debut en la mayor","Oro olímpico, torneo con reglas de edad propias","Subcampeón mundial","Anuncio de retiro y posterior regreso","Primera Copa América con la mayor","Campeón de la Finalissima y del Mundial","Segunda Copa América","Tercera final mundial; retiro anunciado el 31 de agosto","Despedida ante Benín y entrega del honor de la UBA previstas"],goals:"Seis Mundiales, 21 goles",unit:"Goles en cada edición",caption:"Totales por torneo, no goles por partido. Excluyen tandas de penales. El formato de 2026 ofrecía más encuentros que los anteriores.",source:"Fuentes"},
 ar:{timeline:"الأرجنتين: الطريق الطويل إلى الوداع",note:"محطات مختارة. المسافات لا تمثل الزمن المنقضي. موعد 6 أكتوبر مقرر ولم يقع بعد.",rows:["بطولة العالم للشباب والظهور الأول مع المنتخب الأول","ذهب أولمبي في مسابقة ذات قواعد عمرية مستقلة","وصيف كأس العالم","إعلان الاعتزال ثم العودة","أول كوبا أمريكا مع المنتخب الأول","بطل الفيناليسيما وكأس العالم","لقب كوبا أمريكا الثاني","النهائي العالمي الثالث وإعلان الاعتزال في 31 أغسطس","وداع مقرر أمام بنين وتقديم تكريم الجامعة"],goals:"ستة مونديالات و21 هدفا",unit:"الأهداف في كل نسخة",caption:"إجماليات البطولات وليست أهدافا لكل مباراة. لا تشمل ركلات الترجيح. أتاح نظام 2026 مباريات أكثر من النسخ السابقة.",source:"المصادر"}
};
export function MessiFarewellGraphics({locale,kind}:{locale:Locale;kind:"timeline"|"goals"}){
 const c=copy[locale],id=`messi-farewell-${kind}`;
 const refs=kind==="timeline"?[[s.career,"FIFA"],[s.finals,"CONMEBOL"],[s.finalissima,"UEFA"],[s.letter,"AFA"],[s.uba,"UBA"]] as const:[[s.goals,"FIFA · 2006–2022"],[s.statistics2026,"FIFA · 2026"],[s.records,"AFA · 2026"]] as const;
 return <figure id={id} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={`${id}-title`} className="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
 <figcaption id={`${id}-title`} className="font-display text-xl font-bold sm:text-2xl">{kind==="timeline"?c.timeline:c.goals}</figcaption>
 {kind==="timeline"?<><p className="mt-3 text-sm leading-relaxed text-white/75">{c.note}</p><ol className="mt-6 grid gap-4 sm:grid-cols-2">{["2005","2008","2014","2016","2021","2022","2024","2026","06.10.2026"].map((year,i)=><li key={year} className="border-s-2 border-[#e9bd65] ps-4"><span dir="ltr" className="text-lg font-bold text-[#e9bd65]">{year}</span><p className="mt-1 text-sm leading-relaxed">{c.rows[i]}</p></li>)}</ol></>:<><p className="mt-3 text-sm text-white/75">{c.unit}</p><dl className="mt-5 space-y-4">{[1,0,4,1,7,8].map((n,i)=><div key={i} className="grid grid-cols-[3rem_1fr] items-center gap-3"><dt dir="ltr" className="font-bold">{2006+i*4}</dt><dd className="flex items-center gap-3"><span aria-hidden="true" className="h-3 flex-1 rounded bg-white/10"><span className="block h-full rounded bg-[#e9bd65]" style={{width:`${n/8*100}%`}} /></span><span dir="ltr" className="w-4 text-lg font-bold">{n}</span></dd></div>)}</dl><p className="mt-5 text-sm leading-relaxed text-white/75">{c.caption}</p></>}
 <p className="mt-5 text-xs text-white/70">{c.source}</p><ul className="mt-2 flex flex-wrap gap-x-4 gap-y-2 text-sm">{refs.map(([r,label])=><li key={r.url}><a href={r.url} className="text-[#e9bd65] underline">{label}</a></li>)}</ul><p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
 </figure>;
}
