import type { Locale } from "@/lib/i18n/routing";
import { michaelJacksonSources as s } from "@/data/michaelJacksonArticle";
const copy={
 en:{timeline:"Eight moments in a recording career",note:"Selected milestones, not a complete biography. Equal spacing does not represent elapsed time.",rows:["The Jackson 5 break through at Motown; four U.S. number-one singles follow","Off the Wall: an adult solo breakthrough","Thriller begins its extraordinary chart life","Motown 25 brings the moonwalk to a vast TV audience","Bad begins another major album era","Dangerous introduces a different production partnership","HIStory combines a retrospective with new recordings","Invincible, the last studio album released in his lifetime"],records:"Thriller: two different measures",world:"Worldwide sales estimate",us:"U.S. certified album units",worldNote:"More than 67 million copies. Guinness record entry dated August 20, 2021; estimates vary.",usNote:"34 million certified units in 2021, still cited by AP in January 2026. U.S. certification can include streaming equivalents.",warning:"Do not add these figures. The U.S. market is part of the worldwide market, and the methods differ. Neither figure is a real-time sales counter.",source:"Sources"},
 fr:{timeline:"Huit repères dans une carrière discographique",note:"Étapes choisies, pas une biographie complète. Les espacements ne représentent pas les durées.",rows:["Percée des Jackson 5 chez Motown, suivie de quatre numéros un américains","Off the Wall : affirmation d’une carrière solo adulte","Thriller entame son parcours exceptionnel dans les classements","Motown 25 présente le moonwalk à un immense public télévisuel","Bad ouvre une nouvelle grande période","Dangerous et de nouveaux partenaires de production","HIStory associe rétrospective et nouveaux titres","Invincible, dernier album studio publié de son vivant"],records:"Thriller : deux mesures différentes",world:"Estimation des ventes mondiales",us:"Unités d’album certifiées aux États-Unis",worldNote:"Plus de 67 millions d’exemplaires. Fiche Guinness du 20 août 2021 ; les estimations varient.",usNote:"34 millions d’unités certifiées en 2021, encore citées par AP en janvier 2026. La certification peut inclure des équivalents streaming.",warning:"Ne pas additionner ces chiffres. Le marché américain fait partie du marché mondial et les méthodes diffèrent. Aucun chiffre n’est un compteur de ventes en temps réel.",source:"Sources"},
 es:{timeline:"Ocho momentos de una carrera discográfica",note:"Hitos seleccionados, no una biografía completa. El espacio entre ellos no representa el tiempo transcurrido.",rows:["Los Jackson 5 triunfan con Motown y logran cuatro números uno estadounidenses","Off the Wall: consolidación como solista adulto","Thriller inicia su recorrido extraordinario en las listas","Motown 25 lleva el moonwalk a una gran audiencia televisiva","Bad abre otra etapa fundamental","Dangerous incorpora nuevos colaboradores de producción","HIStory combina retrospectiva y grabaciones nuevas","Invincible, último álbum de estudio publicado en vida"],records:"Thriller: dos medidas diferentes",world:"Estimación de ventas mundiales",us:"Unidades de álbum certificadas en EE. UU.",worldNote:"Más de 67 millones de copias. Registro Guinness del 20 de agosto de 2021; las estimaciones varían.",usNote:"34 millones de unidades certificadas en 2021, aún citadas por AP en enero de 2026. La certificación puede incluir equivalentes de streaming.",warning:"No sumar estas cifras. El mercado estadounidense forma parte del mundial y las metodologías difieren. Ninguna es un contador de ventas en tiempo real.",source:"Fuentes"},
 ar:{timeline:"ثماني محطات في المسيرة الموسيقية",note:"محطات مختارة وليست سيرة كاملة. المسافات المتساوية لا تمثل الزمن المنقضي.",rows:["انطلاقة جاكسون فايف مع موتاون، تلتها أربع أغنيات تتصدر القائمة الأمريكية","Off the Wall: انطلاقة ناضجة كفنان منفرد","بداية المسار الاستثنائي لألبوم Thriller في القوائم","موتاون 25 يقدم المون ووك لجمهور تلفزيوني هائل","Bad يفتح مرحلة موسيقية كبرى جديدة","Dangerous وشراكات إنتاج مختلفة","HIStory يجمع مختارات سابقة وتسجيلات جديدة","Invincible، آخر ألبوم استوديو صدر في حياته"],records:"Thriller: مقياسان مختلفان",world:"تقدير المبيعات العالمية",us:"وحدات الألبوم المعتمدة أمريكيا",worldNote:"أكثر من 67 مليون نسخة. صفحة غينيس مؤرخة في 20 أغسطس 2021، والتقديرات متفاوتة.",usNote:"34 مليون وحدة معتمدة في 2021، ظلت أسوشيتد برس تذكرها في يناير 2026. قد يشمل الاعتماد معادلات البث.",warning:"لا تجمع الرقمين. السوق الأمريكية جزء من السوق العالمية، والمنهجان مختلفان. لا يمثل أي رقم عدادا فوريا للمبيعات.",source:"المصادر"}
};
const frame="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6";
export function MichaelJacksonGraphics({locale,kind}:{locale:Locale;kind:"timeline"|"records"}){
 const c=copy[locale],id=`michael-jackson-${kind}`;
 const sources=kind==="timeline"?[[s.grammy,"Recording Academy"],[s.albums,"MichaelJackson.com"],[s.moonwalk,"Smithsonian"]] as const:[[s.sales,"Guinness · 2021"],[s.current,"AP · 2026"],[s.riaa,"RIAA"]] as const;
 return <figure id={id} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={`${id}-title`} className={frame}>
 <figcaption id={`${id}-title`} className="font-display text-xl font-bold sm:text-2xl">{kind==="timeline"?c.timeline:c.records}</figcaption>
 {kind==="timeline"?<><p className="mt-3 text-sm leading-relaxed text-white/75">{c.note}</p><ol className="mt-6 grid gap-4 sm:grid-cols-2">{["1969–1970","1979","1982","1983","1987","1991","1995","2001"].map((year,i)=><li key={year} className="border-s-2 border-[#e9bd65] ps-4"><span dir="ltr" className="text-lg font-bold text-[#e9bd65]">{year}</span><p className="mt-1 text-sm leading-relaxed">{c.rows[i]}</p></li>)}</ol></>:<><dl className="mt-6 grid gap-4 sm:grid-cols-2">{[[c.world,"67m+",c.worldNote],[c.us,"34m",c.usNote]].map(([label,value,note])=><div key={value} className="rounded-lg border border-white/15 p-4"><dt className="text-sm font-semibold">{label}</dt><dd><span dir="ltr" className="my-3 block text-4xl font-bold text-[#e9bd65]">{value}</span><span className="text-sm leading-relaxed text-white/80">{note}</span></dd></div>)}</dl><p className="mt-4 border-s-2 border-red-700 ps-3 text-sm leading-relaxed">{c.warning}</p></>}
 <p className="mt-5 text-xs text-white/70">{c.source}</p><ul className="mt-2 flex flex-wrap gap-x-4 gap-y-2 text-sm">{sources.map(([r,label])=><li key={r.url}><a href={r.url} className="text-[#e9bd65] underline">{label}</a></li>)}</ul><p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
 </figure>;
}
