import type { Locale } from "@/lib/i18n/routing";

const copy = {
  en: { titles: ["A palace world in stages", "Four centres, different settings", "Connections across the sea", "Two scripts, different levels of understanding"], notes: ["Approximate BCE dates. Ordered stages, not an equal-duration scale; regional sequences vary.", "Selected sites, not a complete settlement list or a map of political boundaries.", "Selected documented contacts. These are networks of exchange and influence, not proven imperial territories or measured shipping volumes.", "Reading numerical patterns is different from translating a language. No invented signs or inscriptions are shown."], rows: [["c. 1900–1700 BCE|First Palace period", "c. 1700–1450 BCE|Second Palace period", "c. 1450 BCE onward|Destructions and later Mycenaean administration"], ["Knossos|Northern Crete; largest palatial complex", "Phaistos|Southern Crete; above the Messara plain", "Malia|Northern coast; palace and settlement", "Zakros|Eastern Crete; maritime connections"], ["Cyclades and mainland Greece|Objects, styles and cultural interaction", "Egypt and the Levant|Eastern Mediterranean contacts and exchanged objects"], ["Linear A|Mainly c. 1800–1450 BCE; language undeciphered", "Linear B|Early Greek; deciphered in 1952"]], source: "Sources" },
  fr: { titles: ["Les étapes du monde palatial", "Quatre centres, des milieux différents", "Des liens par la mer", "Deux écritures, deux états de connaissance"], notes: ["Dates approximatives avant notre ère. Étapes ordonnées, sans échelle de durées égales ; variations régionales.", "Sites sélectionnés, pas une liste complète ni une carte de frontières politiques.", "Contacts attestés sélectionnés. Réseaux d’échanges et d’influence, pas territoires impériaux démontrés ni volumes de transport mesurés.", "Comprendre des nombres ne signifie pas traduire une langue. Aucun signe ou texte inventé n’est présenté."], rows: [["v. 1900–1700|Premiers palais", "v. 1700–1450|Nouveaux palais", "À partir de v. 1450|Destructions et administration mycénienne ultérieure"], ["Cnossos|Nord de la Crète ; plus grand complexe", "Phaistos|Sud ; au-dessus de la plaine de la Messara", "Malia|Côte nord ; palais et ville", "Zakros|Est ; contacts maritimes"], ["Cyclades et Grèce continentale|Objets, styles et interactions culturelles", "Égypte et Levant|Contacts et objets échangés en Méditerranée orientale"], ["Linéaire A|Surtout v. 1800–1450 ; langue indéchiffrée", "Linéaire B|Grec ancien ; déchiffré en 1952"]], source: "Sources" },
  es: { titles: ["Las etapas del mundo palacial", "Cuatro centros, distintos entornos", "Conexiones por mar", "Dos escrituras, distinto conocimiento"], notes: ["Fechas aproximadas a. C. Etapas ordenadas, sin escala de duraciones iguales; hay diferencias regionales.", "Lugares seleccionados, no lista completa ni mapa de fronteras políticas.", "Contactos documentados seleccionados. Redes de intercambio e influencia, no territorios imperiales demostrados ni tráfico marítimo cuantificado.", "Reconocer números no equivale a traducir una lengua. No se muestran signos ni inscripciones inventados."], rows: [["c. 1900–1700 a. C.|Primeros palacios", "c. 1700–1450 a. C.|Nuevos palacios", "Desde c. 1450 a. C.|Destrucciones y posterior administración micénica"], ["Cnosos|Norte de Creta; mayor complejo", "Festos|Sur; sobre la llanura de Mesará", "Malia|Costa norte; palacio y asentamiento", "Zakros|Este; conexiones marítimas"], ["Cícladas y Grecia continental|Objetos, estilos e interacción cultural", "Egipto y Levante|Contactos y objetos intercambiados en el Mediterráneo oriental"], ["Lineal A|Principalmente c. 1800–1450 a. C.; lengua sin descifrar", "Lineal B|Griego temprano; descifrado en 1952"]], source: "Fuentes" },
  ar: { titles: ["مراحل العالم القصري", "أربعة مراكز وبيئات مختلفة", "اتصالات عبر البحر", "كتابتان ومستويان من الفهم"], notes: ["تواريخ تقريبية قبل الميلاد. مراحل مرتبة دون مقياس لفترات متساوية، مع اختلافات محلية.", "مواقع مختارة، لا قائمة كاملة للمستوطنات أو خريطة لحدود سياسية.", "اتصالات موثقة مختارة. شبكات تبادل وتأثير وليست أراضي إمبراطورية مثبتة أو أحجام شحن مقاسة.", "تمييز الأرقام مختلف عن ترجمة اللغة. لا نعرض علامات أو نقوشاً مختلقة."], rows: [["نحو 1900–1700 ق.م.|مرحلة القصور الأولى", "نحو 1700–1450 ق.م.|مرحلة القصور الجديدة", "من نحو 1450 ق.م.|دمار وإدارة ميسينية لاحقة"], ["كنوسوس|شمال كريت؛ أكبر مجمع قصري", "فايستوس|الجنوب؛ فوق سهل ميسارا", "ماليا|الساحل الشمالي؛ قصر ومستوطنة", "زاكروس|الشرق؛ اتصالات بحرية"], ["كيكلادس والبر اليوناني|قطع وأساليب وتفاعل ثقافي", "مصر والمشرق|اتصالات وتبادل قطع في شرق المتوسط"], ["الخط أ|أساساً نحو 1800–1450 ق.م.؛ لغة لم تفك رموزها", "الخط ب|يونانية مبكرة؛ فكت رموزه عام 1952"]], source: "المصادر" }
};
const urls = [
  ["https://www.heraklion.gr/en/ourplace/knossos/knossos.html", "https://kclpure.kcl.ac.uk/portal/en/publications/cultural-identity-in-minoan-crete-social-dynamics-in-the-neopalat/"],
  ["https://whc.unesco.org/document/222047"],
  ["https://whc.unesco.org/en/list/1733/", "https://www.metmuseum.org/ru/press-releases/art-of-second-millennium-bc-explored-in-landmark-exhibition-at-metropolitan-museum-2008-exhibitions"],
  ["https://www.repository.cam.ac.uk/items/f50c0df4-f355-4bc0-be2a-8e960b2bb5da", "https://www.cam.ac.uk/research/news/cracking-the-code-the-decipherment-of-linear-b-60-years-on"]
];
const sourceNames = [["Heraklion", "Ellen Adams / Cambridge"], ["ICOMOS / UNESCO"], ["UNESCO", "Metropolitan Museum"], ["Cambridge: Linear A", "Cambridge: Linear B"]];
export function MinoansGraphics({ locale, kind }: { locale: Locale; kind: "timeline" | "palaces" | "trade" | "writing" }) {
  const n = { timeline: 0, palaces: 1, trade: 2, writing: 3 }[kind], c = copy[locale], id = `minoans-${kind}`;
  return <figure id={id} dir={locale === "ar" ? "rtl" : "ltr"} aria-labelledby={`${id}-title`} className="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
    <figcaption id={`${id}-title`} className="font-display text-xl font-bold sm:text-2xl">{c.titles[n]}</figcaption>
    <p className="mt-3 text-sm leading-relaxed text-white/75">{c.notes[n]}</p>
    <ol className={`mt-6 ${kind === "timeline" ? "space-y-5 border-s-2 border-[#e9bd65]/60 ps-5" : "grid gap-5 sm:grid-cols-2"}`}>
      {c.rows[n].map(row => { const [label, detail] = row.split("|"); return <li key={label} className={kind === "timeline" ? "" : "border-s-2 border-[#FF1A1A] ps-4"}><h3 className="font-display text-lg font-bold text-[#e9bd65]">{label}</h3><p className="mt-2 text-sm leading-relaxed text-white/85">{detail}</p></li>; })}
    </ol>
    <p className="mt-5 text-xs leading-relaxed">{c.source}: {urls[n].map((url, i) => <span key={url}>{i > 0 && "; "}<a href={url} className="text-[#e9bd65] underline">{sourceNames[n][i]}</a></span>)}</p>
    <p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
  </figure>;
}
