import type { Locale } from "@/lib/i18n/routing";

const copy = {
  en: {title:"Where the neurons are", note:"Approximate estimates for Octopus vulgaris, summarised in a 2022 review. Not a count for every species or a measure of intelligence.", labels:["Central brain, including optic lobes","Peripheral arm system"], unit:"million neurons", detail:"The central estimate includes about 130 million in the optic lobes and 40 million elsewhere in the central brain. These rounded values total about 520 million, often described as roughly 500 million. Bars share a zero baseline and a 350-million maximum.", source:"Source: Sivitilli, Smith & Gire (2022), neuroanatomical organisation", table:"Accessible data table", area:"Region", value:"Approximate neurons (millions)"},
  fr: {title:"Où se trouvent les neurones", note:"Estimations approximatives pour Octopus vulgaris, reprises dans une synthèse de 2022. Ni un décompte de toutes les espèces ni une mesure d’intelligence.", labels:["Cerveau central, lobes optiques compris","Système périphérique des bras"],unit:"millions de neurones",detail:"L’estimation centrale comprend environ 130 millions dans les lobes optiques et 40 millions ailleurs dans le cerveau central. Le total arrondi de 520 millions est souvent résumé à environ 500 millions. Les barres partent de zéro, avec un maximum commun de 350 millions.",source:"Source : Sivitilli, Smith et Gire (2022), organisation neuroanatomique",table:"Tableau de données accessible",area:"Région",value:"Neurones estimés (millions)"},
  es: {title:"Dónde están las neuronas",note:"Estimaciones aproximadas de Octopus vulgaris recogidas en una revisión de 2022. No representan a todas las especies ni miden la inteligencia.",labels:["Cerebro central, incluidos lóbulos ópticos","Sistema periférico de los brazos"],unit:"millones de neuronas",detail:"La estimación central incluye unos 130 millones en los lóbulos ópticos y 40 millones en el resto del cerebro central. El total redondeado de 520 millones suele resumirse como unos 500 millones. Ambas barras parten de cero y comparten un máximo de 350 millones.",source:"Fuente: Sivitilli, Smith y Gire (2022), organización neuroanatómica",table:"Tabla de datos accesible",area:"Región",value:"Neuronas estimadas (millones)"},
  ar: {title:"أين توجد الخلايا العصبية؟",note:"تقديرات تقريبية للأخطبوط الشائع Octopus vulgaris أوردتها مراجعة عام 2022. لا تمثل جميع الأنواع ولا تقيس الذكاء.",labels:["الدماغ المركزي بما فيه الفصوص البصرية","الجهاز العصبي الطرفي للأذرع"],unit:"مليون خلية عصبية",detail:"يشمل التقدير المركزي نحو 130 مليونا في الفصوص البصرية و40 مليونا في بقية الدماغ المركزي. يبلغ مجموع القيم المقربة نحو 520 مليونا، ويختصر عادة بنحو 500 مليون. يبدأ الشريطان من الصفر وبحد أقصى مشترك قدره 350 مليونا.",source:"المصدر: سيفيتيلي وسميث وغاير (2022)، التنظيم العصبي التشريحي",table:"جدول البيانات المتاح للقراءة",area:"المنطقة",value:"الخلايا المقدرة بالملايين"}
};

export function OctopusMindGraphic({locale}:{locale:Locale}) {
  const c=copy[locale],values=[170,350];
  return <figure id="octopus-neurons" dir={locale==="ar"?"rtl":"ltr"} aria-labelledby="octopus-neurons-title" className="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
    <figcaption id="octopus-neurons-title" className="font-display text-xl font-bold sm:text-2xl">{c.title}</figcaption>
    <p className="mt-3 text-sm leading-relaxed text-white/75">{c.note}</p>
    <div className="mt-6 space-y-5" aria-hidden="true">{values.map((v,i)=><div key={v}>
      <div className="mb-2 flex flex-wrap justify-between gap-x-3 gap-y-1 text-sm"><span>{c.labels[i]}</span><strong>{v} {c.unit}</strong></div>
      <div className="h-5 rounded bg-white/10"><div className="h-5 rounded" style={{width:`${v/350*100}%`,backgroundColor:i===0?'#FF1A1A':'#e9bd65'}} /></div>
    </div>)}</div>
    <p className="mt-5 text-sm leading-relaxed text-white/75">{c.detail}</p>
    <details className="mt-5 text-sm"><summary className="cursor-pointer text-[#e9bd65]">{c.table}</summary><table className="mt-3 w-full text-start"><thead><tr><th scope="col" className="p-2 text-start">{c.area}</th><th scope="col" className="p-2 text-start">{c.value}</th></tr></thead><tbody>{values.map((v,i)=><tr key={v} className="border-t border-white/20"><th scope="row" className="p-2 text-start font-normal">{c.labels[i]}</th><td className="p-2">{v}</td></tr>)}</tbody></table></details>
    <p className="mt-5 text-xs leading-relaxed"><a className="text-[#e9bd65] underline" href="https://pmc.ncbi.nlm.nih.gov/articles/PMC9339708/">{c.source}</a><br /><a className="text-[#e9bd65] underline" href="https://onlinelibrary.wiley.com/doi/10.1002/brv.70125">Biological Reviews (2026), II.2</a></p><p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
  </figure>;
}
