import type { Locale } from "@/lib/i18n/routing";
import { plasticSurgeryData as data } from "@/data/plasticSurgeryData";

const copy = {
  en: {
    titles: ["35.2 million procedures: what the survey counts", "The most common procedures in 2025", "Gender and age: different denominators", "Country activity: estimated procedures", "Procedure-specific risks: evidence and limits"],
    date: "ISAPS 2025, released September 29, 2026. Verified October 10, 2026.",
    source: "Read the official ISAPS tables and methodology", scroll: "Scroll horizontally to read the complete table.",
    groups: ["Surgical", "Non-surgical", "Total"], change: "Comparable-category annual change", count: "Estimated procedures", procedure: "Procedure", country: "Country", women: "Women", men: "Men", risk: "Important risks", limit: "Evidence and limitations",
    totalNote: "2,900 responding plastic surgeons; worldwide extrapolation. Added categories and coverage changes mean raw totals and comparable-category changes differ. Procedures are not unique patients or all providers’ activity.",
    topNote: "Bars start at zero, scaled to the largest count within each group. Counts are estimates, not patients.",
    ageNote: "Gender shares are within surgical or non-surgical procedures, using the survey’s female/male categories. Age shares are within each listed procedure. Two adult age bands are shown, not the entire distribution.",
    countryNote: "Highest estimated total volumes among reported countries. Not revenue, resident prevalence, per-capita activity or a safety ranking. Published totals may differ slightly from component sums because of rounding.",
    riskNote: "Different procedures, populations and outcome definitions prevent a universal risk ranking. Absence of a rate here does not mean absence of risk.",
    surgical: ["Eyelid surgery", "Liposuction", "Breast augmentation", "Breast lift", "Tummy tuck", "Rhinoplasty"],
    nonSurgical: ["Botulinum toxin", "Hyaluronic acid fillers", "Skin tightening", "Hair removal", "Chemical peel"],
    countries: ["United States", "Brazil", "China", "Japan", "South Korea", "Germany", "Italy", "Mexico", "Turkey", "India"],
    risks: [
      ["Surgery generally", "Anesthesia, infection, bleeding, clots, scars and nerve injury", "Depends on operation, health, setting and follow-up; no single worldwide rate."],
      ["Tummy tuck", "Major complications; combined operations need particular assessment", "4.0% in 25,478 US CosmetAssure patients, 2008–2013; published 2015. Historical major-event definition, not all complications or a 2026 global rate."],
      ["Breast implants", "Rupture, capsular contracture, reoperation; BIA-ALCL particularly associated with textured implants", "Not lifetime devices. Risk varies by device and surveillance."],
      ["Eyelid surgery", "Dry eyes, closure problems and rare vision injury", "Procedure-specific ASPS guidance; no universal incidence asserted."],
      ["Gluteal fat grafting / BBL", "Fat embolism, potentially fatal", "2022 joint safety guidance supports ultrasound verification of subcutaneous placement above muscle fascia; not a zero-risk guarantee."],
      ["Dermal fillers", "Vascular occlusion, tissue death, blindness or stroke", "FDA warning. Rare serious events; reports alone cannot establish universal incidence."],
      ["Botulinum toxin", "Bruising or weakness; warning about toxin spread", "BOTOX Cosmetic label notes no confirmed serious distant spread at recommended cosmetic doses for listed indications. Product and dose matter."]
    ], riskSources: "Sources: ASPS, FDA, BOTOX Cosmetic label and Winocour’s historical study. Each row links to its evidence. Verified October 10, 2026."
  },
  fr: {
    titles: ["35,2 millions d’actes : le périmètre du sondage", "Les interventions les plus fréquentes en 2025", "Sexe et âge : des dénominateurs différents", "Activité par pays : interventions estimées", "Risques par intervention : preuves et limites"],
    date: "ISAPS 2025, publié le 29 septembre 2026. Vérifié le 10 octobre 2026.", source: "Lire les tableaux et la méthode officiels ISAPS", scroll: "Faites défiler horizontalement pour lire le tableau complet.",
    groups: ["Chirurgical", "Non chirurgical", "Total"], change: "Variation annuelle à catégories comparables", count: "Interventions estimées", procedure: "Intervention", country: "Pays", women: "Femmes", men: "Hommes", risk: "Risques importants", limit: "Données et limites",
    totalNote: "2 900 chirurgiens répondants ; extrapolation mondiale. Nouvelles catégories et couverture modifiée expliquent les différences entre totaux bruts et variations comparables. Les actes ne sont ni des patients uniques ni toute l’activité des praticiens.",
    topNote: "Les barres partent de zéro et sont proportionnelles au maximum de chaque groupe. Il s’agit d’estimations d’actes, pas de patients.", ageNote: "Les parts femmes/hommes concernent les actes chirurgicaux ou non chirurgicaux. Les parts par âge concernent chaque intervention. Deux tranches adultes sont affichées, pas toute la distribution.",
    countryNote: "Principaux volumes totaux estimés des pays publiés. Ni revenus, ni prévalence résidentielle, ni classement par habitant ou de sécurité. Les arrondis peuvent expliquer de petits écarts entre totaux et composantes.", riskNote: "Les procédures, populations et définitions diffèrent : aucun classement universel du risque n’est possible. L’absence d’un taux ne signifie pas l’absence de risque.",
    surgical: ["Chirurgie des paupières", "Liposuccion", "Augmentation mammaire", "Lifting mammaire", "Abdominoplastie", "Rhinoplastie"], nonSurgical: ["Toxine botulique", "Comblement à l’acide hyaluronique", "Raffermissement cutané", "Épilation", "Peeling chimique"], countries: ["États-Unis", "Brésil", "Chine", "Japon", "Corée du Sud", "Allemagne", "Italie", "Mexique", "Turquie", "Inde"],
    risks: [["Chirurgie en général", "Anesthésie, infection, saignement, thrombose, cicatrices et lésions nerveuses", "Dépend du geste, de la santé, du cadre et du suivi ; pas de taux mondial unique."], ["Abdominoplastie", "Complications majeures ; prudence avec les opérations combinées", "4,0 % chez 25 478 patients américains CosmetAssure, 2008–2013 ; étude de 2015. Événements majeurs historiques, pas tous les problèmes ni un taux mondial 2026."], ["Implants mammaires", "Rupture, contracture capsulaire, reprises ; BIA-ALCL surtout lié aux implants texturés", "Pas des dispositifs à vie. Risque propre au dispositif et au suivi."], ["Chirurgie des paupières", "Sécheresse, fermeture difficile, rares lésions visuelles", "Guide ASPS spécifique ; aucune incidence universelle affirmée."], ["Transfert de graisse / BBL", "Embolie graisseuse potentiellement mortelle", "Guide conjoint 2022 : échographie pour vérifier un dépôt sous-cutané au-dessus du fascia musculaire. Pas de garantie de risque nul."], ["Produits de comblement", "Occlusion vasculaire, nécrose, cécité ou AVC", "Avertissement FDA. Événements graves rares ; les signalements seuls ne donnent pas une incidence universelle."], ["Toxine botulique", "Ecchymoses, faiblesse ; avertissement sur la diffusion", "Notice BOTOX Cosmetic : pas de diffusion distante grave confirmée aux doses cosmétiques recommandées pour les indications listées. Produit et dose comptent."]], riskSources: "Sources : ASPS, FDA, notice BOTOX Cosmetic et étude historique de Winocour. Chaque ligne renvoie à ses données."
  },
  es: {
    titles: ["35,2 millones de procedimientos: qué mide la encuesta", "Procedimientos más frecuentes en 2025", "Género y edad: denominadores distintos", "Actividad por país: procedimientos estimados", "Riesgos específicos: evidencia y límites"], date: "ISAPS 2025, publicado el 29 de septiembre de 2026. Verificado el 10 de octubre de 2026.", source: "Consultar tablas y metodología oficiales de ISAPS", scroll: "Desplace horizontalmente para leer toda la tabla.",
    groups: ["Quirúrgicos", "No quirúrgicos", "Total"], change: "Cambio anual en categorías comparables", count: "Procedimientos estimados", procedure: "Procedimiento", country: "País", women: "Mujeres", men: "Hombres", risk: "Riesgos importantes", limit: "Evidencia y limitaciones",
    totalNote: "2.900 cirujanos participantes; extrapolación mundial. Nuevas categorías y cambios de cobertura diferencian totales brutos y variaciones comparables. No son pacientes únicos ni toda la actividad de todos los proveedores.", topNote: "Las barras parten de cero y se escalan al máximo de cada grupo. Son procedimientos estimados, no pacientes.", ageNote: "Porcentajes mujer/hombre dentro de procedimientos quirúrgicos o no quirúrgicos. Los grupos de edad son proporciones de cada procedimiento. Se muestran dos franjas adultas, no toda la distribución.", countryNote: "Mayores volúmenes totales estimados entre países publicados. No son ingresos, prevalencia residente, clasificación por habitante ni de seguridad. El redondeo puede producir pequeñas diferencias entre componentes y totales.", riskNote: "Procedimientos, poblaciones y definiciones impiden ordenar universalmente el riesgo. No mostrar una tasa no significa que no haya riesgo.", surgical: ["Cirugía de párpados", "Liposucción", "Aumento mamario", "Elevación mamaria", "Abdominoplastia", "Rinoplastia"], nonSurgical: ["Toxina botulínica", "Rellenos de ácido hialurónico", "Tensado cutáneo", "Depilación", "Peeling químico"], countries: ["Estados Unidos", "Brasil", "China", "Japón", "Corea del Sur", "Alemania", "Italia", "México", "Turquía", "India"],
    risks: [["Cirugía general", "Anestesia, infección, sangrado, trombos, cicatrices y lesión nerviosa", "Depende de operación, salud, entorno y seguimiento; sin tasa mundial única."], ["Abdominoplastia", "Complicaciones mayores; valorar especialmente las combinaciones", "4,0 % en 25.478 pacientes estadounidenses CosmetAssure, 2008–2013; estudio de 2015. Eventos mayores históricos, no todas las complicaciones ni tasa global 2026."], ["Implantes mamarios", "Rotura, contractura capsular, revisiones; BIA-ALCL especialmente asociado a implantes texturizados", "No son dispositivos vitalicios. Riesgo específico del producto y vigilancia."], ["Cirugía de párpados", "Sequedad, problemas de cierre y lesión visual infrecuente", "Guía específica ASPS; sin incidencia universal afirmada."], ["Injerto glúteo de grasa / BBL", "Embolia grasa potencialmente mortal", "Guía conjunta 2022: ecografía para verificar colocación subcutánea sobre la fascia muscular. No garantiza riesgo cero."], ["Rellenos dérmicos", "Oclusión vascular, necrosis, ceguera o ictus", "Advertencia FDA. Eventos graves infrecuentes; las notificaciones no dan una incidencia universal."], ["Toxina botulínica", "Hematomas, debilidad; advertencia sobre difusión", "Ficha BOTOX Cosmetic: sin difusión distante grave confirmada a dosis cosméticas recomendadas para indicaciones listadas. Importan producto y dosis."]], riskSources: "Fuentes: ASPS, FDA, ficha BOTOX Cosmetic y estudio histórico de Winocour. Cada fila enlaza su evidencia."
  },
  ar: {
    titles: ["35.2 مليون إجراء: ماذا يقيس المسح؟", "الإجراءات الأكثر شيوعا في 2025", "النوع والعمر: مقامات مختلفة", "نشاط البلدان: إجراءات مقدرة", "المخاطر بحسب الإجراء: الأدلة والحدود"], date: "مسح ISAPS 2025، صدر في 29 سبتمبر 2026. التحقق في 10 أكتوبر 2026.", source: "اقرأ جداول ISAPS الرسمية ومنهجيتها", scroll: "مرر أفقيا لقراءة الجدول كاملا.", groups: ["جراحية", "غير جراحية", "الإجمالي"], change: "التغير السنوي للفئات المتجانسة", count: "عدد الإجراءات المقدر", procedure: "الإجراء", country: "البلد", women: "نساء", men: "رجال", risk: "مخاطر مهمة", limit: "الأدلة والحدود",
    totalNote: "شارك 2,900 جراح؛ الأعداد تقديرات عالمية. تغير التغطية وإضافة الفئات يفسران اختلاف الإجماليات الخام عن التغير المتجانس. الإجراءات ليست أشخاصا فريدين ولا نشاط جميع مقدمي الخدمة.", topNote: "تبدأ الأعمدة من الصفر وتتناسب مع أعلى عدد داخل كل مجموعة. الأعداد إجراءات مقدرة وليست مرضى.", ageNote: "حصص النساء والرجال ضمن الجراحة أو غير الجراحة وفق فئات المسح. حصص العمر ضمن كل إجراء. نعرض فئتين بالغتين لا كامل التوزيع.", countryNote: "أعلى إجماليات مقدرة بين البلدان المنشورة. ليست إيرادات أو انتشارا بين السكان أو ترتيب الفرد أو السلامة. قد يفسر التقريب فروقا صغيرة بين المكونات والإجمالي.", riskNote: "اختلاف الإجراءات والمجموعات وتعريف النتائج يمنع ترتيبا عالميا للمخاطر. عدم ذكر معدل لا يعني عدم وجود خطر.", surgical: ["جراحة الجفون", "شفط الدهون", "تكبير الثدي", "رفع الثدي", "شد البطن", "تجميل الأنف"], nonSurgical: ["توكسين البوتولينوم", "فيلر حمض الهيالورونيك", "شد الجلد", "إزالة الشعر", "التقشير الكيميائي"], countries: ["الولايات المتحدة", "البرازيل", "الصين", "اليابان", "كوريا الجنوبية", "ألمانيا", "إيطاليا", "المكسيك", "تركيا", "الهند"],
    risks: [["الجراحة عموما", "التخدير والعدوى والنزف والجلطات والندوب وأذى الأعصاب", "تتغير بحسب العملية والصحة والمنشأة والمتابعة؛ لا معدل عالمي واحد."], ["شد البطن", "مضاعفات كبرى؛ تقييم خاص عند جمع العمليات", "4.0% في 25,478 مريضا أمريكيا بقاعدة CosmetAssure خلال 2008–2013، دراسة 2015. أحداث كبرى تاريخية وليست جميع المضاعفات أو معدل 2026 العالمي."], ["زرعات الثدي", "تمزق وتقلص كبسولي وإعادة جراحة؛ BIA-ALCL يرتبط خصوصا بالسطح المحبب", "ليست أجهزة مدى الحياة. يختلف الخطر بحسب الجهاز والمراقبة."], ["جراحة الجفون", "جفاف وصعوبة إغلاق وأذى بصري نادر", "إرشادات ASPS خاصة بالإجراء دون معدل عالمي."], ["حقن دهون الأرداف / BBL", "انصمام دهني قد يكون قاتلا", "إرشادات مشتركة 2022 تؤيد الإيكو للتحقق من الوضع تحت الجلد فوق لفافة العضلات. لا ضمان لخطر صفري."], ["الفيلر", "انسداد وعائي وموت أنسجة وعمى أو سكتة", "تحذير FDA. أحداث خطيرة نادرة؛ البلاغات وحدها لا تحدد معدل حدوث عالمي."], ["توكسين البوتولينوم", "كدمات وضعف؛ تحذير انتشار تأثير السم", "نشرة BOTOX Cosmetic: لا انتشار بعيد خطير مؤكد بالجرعات التجميلية الموصى بها للاستطبابات المذكورة. المادة والجرعة مهمتان."]], riskSources: "المصادر: ASPS وFDA ونشرة BOTOX Cosmetic ودراسة وينوكور التاريخية. ترتبط كل سطر بأدلته."
  }
};
const riskLinks = ["https://www.plasticsurgery.org/cosmetic-procedures", "https://ednet.plasticsurgery.org/Listing/Abdominoplasty-Risk-Factors-Complication-Rates-and-Safety-of-Combined-Procedures-10707", "https://www.fda.gov/medical-devices/breast-implants/risks-and-complications-breast-implants", "https://www.plasticsurgery.org/cosmetic-procedures/eyelid-surgery/safety", "https://www.plasticsurgery.org/for-medical-professionals/publications/psn-extra/news/gluteal-fat-grafting-a-joint-safety-statement", "https://www.fda.gov/medical-devices/aesthetic-cosmetic-devices/dermal-fillers-soft-tissue-fillers", "https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=485d9b71-6881-42c5-a620-a4360c7192ab"];
export type PlasticGraphicKind = "totals" | "procedures" | "demographics" | "countries" | "risks";
export function PlasticSurgeryGraphics({ locale, kind }: { locale: Locale; kind: PlasticGraphicKind }) {
  const t = copy[locale], index = ["totals", "procedures", "demographics", "countries", "risks"].indexOf(kind);
  const nf = new Intl.NumberFormat(locale === "ar" ? "ar-u-nu-latn" : locale);
  const number = (n: number) => nf.format(n);
  const cell = "border-b border-white/15 p-3 text-start leading-relaxed";
  const header = "border-b border-white/30 p-3 text-start";
  function table(headers: string[], rows: (string | number)[][], links?: string[]) {
    return <div role="region" aria-label={t.titles[index]} tabIndex={0} className="mt-4 overflow-x-auto focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#D9AD55]"><table className={`w-full border-collapse text-sm ${kind === "risks" ? "min-w-[620px]" : "min-w-[480px]"}`}><caption className="sr-only">{t.titles[index]}</caption><thead><tr>{headers.map(h => <th key={h} scope="col" className={header}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((value, j) => j === 0 ? <th key={j} scope="row" className={`${cell} font-medium`}>{links ? <a href={links[i]} className="underline underline-offset-4 hover:text-[#D9AD55]">{value}</a> : value}</th> : <td key={j} className={cell}>{typeof value === "number" ? <bdi>{number(value)}</bdi> : value}</td>)}</tr>)}</tbody></table></div>;
  }
  function bars(labels: string[], values: readonly number[]) {
    const max = Math.max(...values);
    return <ol className="mt-4 space-y-4">{values.map((v, i) => <li key={labels[i]} className="text-sm"><div className="flex flex-wrap justify-between gap-2"><span>{labels[i]}</span><strong><bdi>{number(v)}</bdi></strong></div><div aria-hidden="true" className="mt-2 h-3 rounded bg-white/10"><div className="h-3 rounded bg-[#D9AD55]" style={{width:`${v/max*100}%`}} /></div></li>)}</ol>;
  }
  const note = kind === "totals" ? t.totalNote : kind === "procedures" ? t.topNote : kind === "demographics" ? t.ageNote : kind === "countries" ? t.countryNote : t.riskNote;
  return <figure dir={locale === "ar" ? "rtl" : "ltr"} aria-labelledby={`plastic-${kind}`} className="my-8 min-w-0 scroll-mt-28 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
    <p className="text-xs font-semibold uppercase tracking-widest text-[#E53935]">PRESDA Data Graphics</p><figcaption id={`plastic-${kind}`} className="mt-3 text-xl font-bold text-[#D9AD55]">{t.titles[index]}</figcaption><p className="mt-3 text-xs text-white/70">{kind === "risks" ? t.riskSources : t.date}</p><p className="mt-3 text-sm leading-relaxed text-white/80">{note}</p>
    {kind !== "procedures" && <p className="mt-2 text-xs text-white/70">{t.scroll}</p>}
    {kind === "totals" && table([t.procedure,t.count,t.change],t.groups.map((g,i)=>[g,data.totals[i],`${data.comparableChange[i]}%`]))}
    {kind === "procedures" && <><h3 className="mt-6 font-bold">{t.groups[0]}</h3>{bars(t.surgical,data.surgical)}<h3 className="mt-6 font-bold">{t.groups[1]}</h3>{bars(t.nonSurgical,data.nonSurgical)}</>}
    {kind === "demographics" && <>{table([t.procedure,t.women,t.men],t.groups.slice(0,2).map((g,i)=>[g,`${data.women[i]}%`,`${data.men[i]}%`]))}{table([t.procedure,"18–34","35–50"],[t.surgical[2],t.surgical[5],t.surgical[1],t.nonSurgical[0]].map((p,i)=>[p,`${data.ages[i][0]}%`,`${data.ages[i][1]}%`]))}</>}
    {kind === "countries" && table([t.country,...t.groups],t.countries.map((c,i)=>[c,...data.countries[i]]))}
    {kind === "risks" && table([t.procedure,t.risk,t.limit],t.risks,riskLinks)}
    {kind !== "risks" && <a href={data.source} className="mt-5 inline-block text-xs underline underline-offset-4 hover:text-[#D9AD55]">{t.source}</a>}
  </figure>;
}
