import type { Locale } from "@/lib/i18n/routing";
import { seoulSources as s } from "@/data/seoulArticle";

// Source-backed editorial lists, rendered on the server. Dates are milestones,
// not a continuous time scale, and the belt is a structured guide, not a map.
const copy={
 en:{belt:"Where the Physical AI plan takes shape",beltNote:"Structured location guide, not a geographic map. Existing anchors and proposed developments are distinct.",nodes:[["Yangjae · AI research","Existing anchor: Seoul AI Hub. AI Tech City construction targeted to begin in 2028."],["Suseo · Robotics","Robot Plus Test Field opened in 2024. Robot Tech Center completion targeted for 2030."],["Yongsan · Separate proposed showcase","Planned intelligent business district, including connected operations and logistics. Not a completed third belt hub."]],timeline:"Operating, being tested, or still planned?",note:"Selected milestones reviewed October 3, 2026. Spacing does not represent elapsed time. A public pilot can carry real passengers while retaining restrictions.",events:[["2024","Existing facility","Robot Plus Test Field opens in Suseo."],["April 2026","Public pilot","A148 early-morning autonomous bus launches; seated passengers only."],["August 2026 notice","City-reported snapshot","24 autonomous vehicles: 16 buses, 7 taxis and 1 demand-responsive vehicle, across six districts."],["November 2026","Revised target","Sangam Level 4 robotaxi service. August notice supersedes earlier October expectation."],["2028","Construction target","Start of AI Tech City construction, not completion."],["2030","Development targets","Robot Tech Center completion; separately, a city fleet target of 500 autonomous buses."]],source:"Sources",limits:"Targets are not achieved outcomes. Separate city notices report different snapshots; do not combine their fleet counts."},
 fr:{belt:"Où se dessine le projet d’IA physique",beltNote:"Guide structuré, pas une carte géographique. Les équipements existants sont distingués des projets.",nodes:[["Yangjae · Recherche en IA","Point d’appui existant : Seoul AI Hub. Début des travaux d’AI Tech City visé pour 2028."],["Suseo · Robotique","Robot Plus Test Field ouvert en 2024. Achèvement du Robot Tech Center visé pour 2030."],["Yongsan · Vitrine distincte projetée","Quartier d’affaires intelligent prévu, avec opérations et logistique connectées. Ce n’est pas un troisième pôle achevé."]],timeline:"En service, en essai ou encore prévu ?",note:"Étapes choisies, vérifiées le 3 octobre 2026. L’espacement ne représente pas la durée. Un pilote public peut transporter des passagers tout en restant limité.",events:[["2024","Équipement existant","Ouverture de Robot Plus Test Field à Suseo."],["Avril 2026","Pilote public","Lancement du bus autonome matinal A148 ; passagers assis uniquement."],["Notice d’août 2026","Bilan municipal daté","24 véhicules autonomes : 16 bus, 7 taxis et 1 véhicule à la demande, dans six arrondissements."],["Novembre 2026","Objectif révisé","Robotaxi de niveau 4 à Sangam. La notice d’août remplace l’échéance initiale d’octobre."],["2028","Objectif de chantier","Début des travaux d’AI Tech City, pas leur achèvement."],["2030","Objectifs de développement","Achèvement du Robot Tech Center ; séparément, objectif municipal de 500 bus autonomes."]],source:"Sources",limits:"Les objectifs ne sont pas des résultats acquis. Les annonces présentent des décomptes distincts qui ne doivent pas être fusionnés."},
 es:{belt:"Dónde toma forma el plan de IA física",beltNote:"Guía estructurada, no mapa geográfico. Distingue instalaciones existentes y proyectos previstos.",nodes:[["Yangjae · Investigación en IA","Base existente: Seoul AI Hub. Inicio de construcción de AI Tech City previsto para 2028."],["Suseo · Robótica","Robot Plus Test Field abrió en 2024. Finalización del Robot Tech Center prevista para 2030."],["Yongsan · Vitrina propuesta aparte","Distrito inteligente de negocios proyectado, con operaciones y logística conectadas. No es un tercer polo terminado."]],timeline:"¿En servicio, en pruebas o todavía previsto?",note:"Hitos seleccionados, revisados el 3 de octubre de 2026. El espaciado no representa el tiempo transcurrido. Un piloto puede llevar pasajeros reales y mantener restricciones.",events:[["2024","Instalación existente","Abre Robot Plus Test Field en Suseo."],["Abril de 2026","Piloto público","Empieza el autobús autónomo de madrugada A148; todos los pasajeros sentados."],["Nota de agosto de 2026","Balance municipal fechado","24 vehículos autónomos: 16 autobuses, 7 taxis y 1 vehículo bajo demanda, en seis distritos."],["Noviembre de 2026","Objetivo revisado","Robotaxi de nivel 4 en Sangam. La nota de agosto sustituye la previsión de octubre."],["2028","Objetivo de construcción","Inicio de las obras de AI Tech City, no finalización."],["2030","Metas de desarrollo","Finalización de Robot Tech Center; por separado, meta municipal de 500 autobuses autónomos."]],source:"Fuentes",limits:"Las metas no son resultados logrados. Los anuncios presentan recuentos distintos que no deben combinarse."},
 ar:{belt:"أين تتشكل خطة الذكاء الاصطناعي المادي؟",beltNote:"دليل منظم للمواقع وليس خريطة جغرافية. يفصل المنشآت القائمة عن المشاريع المقترحة.",nodes:[["يانغجي · أبحاث الذكاء الاصطناعي","مرتكز قائم: Seoul AI Hub. يستهدف بدء بناء AI Tech City في 2028."],["سوسو · الروبوتات","افتتح Robot Plus Test Field في 2024. يستهدف اكتمال Robot Tech Center في 2030."],["يونغسان · نموذج مقترح منفصل","منطقة أعمال ذكية مخططة بعمليات ولوجستيات مترابطة، وليست عقدة ثالثة مكتملة في الحزام."]],timeline:"قائم أم تجريبي أم لا يزال مخططاً؟",note:"محطات مختارة روجعت في 3 أكتوبر 2026. المسافات لا تمثل المدد. قد ينقل المشروع التجريبي ركاباً حقيقيين مع بقائه مقيداً.",events:[["2024","منشأة قائمة","افتتاح Robot Plus Test Field في سوسو."],["أبريل 2026","خدمة تجريبية عامة","إطلاق حافلة الفجر الذاتية A148 مع اشتراط جلوس الركاب."],["بيان أغسطس 2026","حصيلة بلدية مؤرخة","24 مركبة ذاتية: 16 حافلة و7 سيارات أجرة ومركبة حسب الطلب، في ست مناطق."],["نوفمبر 2026","هدف معدل","روبوتاكسي المستوى الرابع في سانغام. يحل بيان أغسطس محل توقع أكتوبر السابق."],["2028","هدف لبدء البناء","بدء أعمال AI Tech City وليس اكتمالها."],["2030","أهداف تطوير","اكتمال Robot Tech Center؛ وهدف منفصل لأسطول بلدي من 500 حافلة ذاتية."]],source:"المصادر",limits:"الأهداف ليست إنجازات متحققة. تورد البيانات حصائل مختلفة لا ينبغي دمجها."}
};
export function SeoulGraphics({locale,kind}:{locale:Locale;kind:"belt"|"timeline"}){
 const c=copy[locale],id=`seoul-${kind}`;
 const refs=kind==="belt"?[s.strategy,s.belt]:[s.belt,s.buses,s.fleet,s.taxis,s.strategy,s.fleet];
 const labels=kind==="belt"?["Seoul · 2026","Seoul · Yangjae / Suseo"]:["Seoul · Suseo","Seoul · A148","Seoul · 2026-08","Seoul · Sangam","Seoul · 2026-01","Seoul · 2030"];
 return <figure id={id} dir={locale==="ar"?"rtl":"ltr"} aria-labelledby={`${id}-title`} className="flow-root my-10 rounded-xl border border-white/20 bg-[#101010] p-4 text-white sm:p-6">
 <figcaption id={`${id}-title`} className="font-display text-xl font-bold sm:text-2xl">{kind==="belt"?c.belt:c.timeline}</figcaption>
 <p className="mt-3 text-sm leading-relaxed text-white/75">{kind==="belt"?c.beltNote:c.note}</p>
 {kind==="belt"?<ol className="my-5 space-y-4">{c.nodes.map(([name,description],i)=><li key={name} className={`${i===2?"border-white/40":"border-[#e9bd65]"} border-s-4 ps-4`}><h3 className="text-base font-bold text-[#e9bd65]">{name}</h3><p className="mt-2 text-sm leading-relaxed">{description}</p></li>)}</ol>:<ol className="my-5 grid gap-5 sm:grid-cols-2">{c.events.map(([date,status,description],i)=><li key={date} className="border-s-2 border-[#e9bd65] ps-4"><p className="font-bold text-[#e9bd65]">{date}</p><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-white/80">{status}</p><p className="mt-2 text-sm leading-relaxed">{description} <a href={refs[i].url} aria-label={`${c.source}: ${date}`} className="text-[#e9bd65] underline">[{i+1}]</a>{i===5&&<> <a href={s.belt.url} aria-label={`${c.source}: Suseo`} className="text-[#e9bd65] underline">[7]</a></>}</p></li>)}</ol>}
 {kind==="timeline"&&<p className="border-t border-white/20 pt-4 text-sm leading-relaxed text-white/75">{c.limits}</p>}
 <p className="mt-5 text-xs text-white/70">{c.source}</p><ul className="mt-2 flex flex-wrap gap-x-4 gap-y-2 text-sm">{refs.map((r,i)=><li key={`${r.url}-${i}`}><a href={r.url} className="text-[#e9bd65] underline">{labels[i]}</a></li>)}</ul>
 <p className="mt-4 text-xs text-white/60">PRESDA Data Graphics</p>
 </figure>;
}
