import type { Locale } from "@/lib/i18n/routing";

export type SonghaiGraphicKind = "timeline" | "rulers" | "cities" | "economy" | "invasion";
const copy = {
  en: {
    titles: ["Songhai: a chronology with its limits", "The people who shaped the turning points", "The Niger world: three distinct urban roles", "How the economy connected regions", "1590–1591: invasion across the Sahara"],
    brand: "PRESDA DATA GRAPHICS", source: "Sources and context", date: "Date / period", event: "Event", person: "Person", role: "Role", goods: "Goods / activity", connection: "Connection", limit: "What the evidence does not measure", scroll: "Scroll horizontally to read the full table.",
    timeline: [["First millennium CE", "Gao area's early settlements and trade, documented archaeologically"], ["1464–1492", "Sunni Ali's reign and imperial expansion"], ["1468", "Capture of Timbuktu; University of Cape Town chronology"], ["1470s", "Djenné brought under Songhai control; approximate date"], ["1493–1528", "Askia Muhammad's reign"], ["1495", "Tomb of Askia, as dated by UNESCO"], ["1496–1498", "Askia Muhammad's pilgrimage"], ["1528", "Askia Muhammad deposed"], ["1590", "Saadian expedition sent under Judar Pasha"], ["13 March 1591", "Tondibi: date given by Nobili's 2022 study"], ["1591–1612", "Resistance period analyzed by Kaba; overlaps occupation"], ["1594", "Exile of prominent Timbuktu scholars"]],
    rulers: [["Sunni Ali", "1464–1492", "Songhai ruler; military expansion"], ["Askia Muhammad", "1493–1528", "Songhai ruler; administration and scholarly patronage"], ["Askia Ishaq II", "Tondibi, 1591", "Songhai ruler whose forces faced the expedition"], ["Ahmad al-Mansur", "Invasion ordered, 1590", "Saadian Moroccan sultan; did not command Tondibi"], ["Judar Pasha", "Expedition, 1590–1591", "Field commander, not a Songhai ruler"]],
    economy: [["Gold", "Northbound trans-Saharan exchange", "No audited empire-wide tonnage or modern-dollar valuation"], ["Salt", "Saharan supply to Sahelian markets", "No single fixed gold-to-salt price for all markets"], ["Food, fish and livestock", "Local production and river exchange", "No reliable empire-wide production total"], ["Cloth and horses", "Imports and regional exchange", "No complete annual import ledger"], ["Manuscripts", "Copyists, merchants, scholars and libraries", "No census of all imperial books or students"]],
    cities: ["Gao", "Timbuktu", "Djenné", "Niger", "Bani / inland delta", "Dendi"], cityRoles: ["Gao: principal political capital", "Timbuktu: scholarship and commerce", "Djenné: agriculture and regional trade"],
    route: ["Morocco", "Sahara", "Tondibi", "Gao", "1590 departure", "1591 arrival"],
    mapNote: "Historical schematic, not to scale. River geometry is simplified; symbols show connections, not precise borders or the empire's full extent.",
    invasionNote: "General direction only, not a verified daily itinerary. Troop totals and tactical details vary across accounts. The campaign was ordered by Ahmad al-Mansur and commanded by Judar Pasha.",
    timelineNote: "Chronicle traditions and modern accounts do not agree on every detail. Approximate dates remain approximate; overlapping periods do not imply that resistance ended everywhere in 1612.",
    economyNote: "This is a network comparison, not quantified trade flows, GDP or an estimate of royal net worth. Enslavement and coerced labor are addressed in the article, not converted into commodity prices here."
  },
  fr: {
    titles: ["Songhaï : une chronologie et ses limites", "Les acteurs des grands tournants", "Le monde du Niger : trois fonctions urbaines", "Comment l'économie reliait les régions", "1590–1591 : une invasion par le Sahara"],
    brand: "PRESDA DATA GRAPHICS", source: "Sources et contexte", date: "Date / période", event: "Événement", person: "Personne", role: "Fonction", goods: "Biens / activité", connection: "Relation", limit: "Ce que les sources ne mesurent pas", scroll: "Faites défiler horizontalement pour lire le tableau complet.",
    timeline: [["Premier millénaire", "Établissements et échanges anciens autour de Gao, attestés par l'archéologie"], ["1464–1492", "Règne de Sonni Ali et expansion impériale"], ["1468", "Prise de Tombouctou selon la chronologie de l'Université du Cap"], ["Années 1470", "Djenné passe sous contrôle songhaï ; date approximative"], ["1493–1528", "Règne d'Askia Mohammed"], ["1495", "Tombeau des Askia, datation de l'UNESCO"], ["1496–1498", "Pèlerinage d'Askia Mohammed"], ["1528", "Déposition d'Askia Mohammed"], ["1590", "Envoi de l'expédition saadienne de Judar Pacha"], ["13 mars 1591", "Tondibi : date donnée par l'étude de Nobili de 2022"], ["1591–1612", "Période de résistance étudiée par Kaba, parallèle à l'occupation"], ["1594", "Exil de savants éminents de Tombouctou"]],
    rulers: [["Sonni Ali", "1464–1492", "Souverain songhaï ; expansion militaire"], ["Askia Mohammed", "1493–1528", "Souverain songhaï ; administration et soutien aux savants"], ["Askia Ishaq II", "Tondibi, 1591", "Souverain songhaï dont les forces affrontèrent l'expédition"], ["Ahmad al-Mansur", "Invasion ordonnée, 1590", "Sultan saadien du Maroc ; n'a pas commandé Tondibi"], ["Judar Pacha", "Expédition, 1590–1591", "Commandant de terrain, pas un souverain songhaï"]],
    economy: [["Or", "Échanges transsahariens vers le nord", "Pas de tonnage impérial vérifié ni de valeur en dollars modernes"], ["Sel", "Approvisionnement saharien des marchés du Sahel", "Pas de prix or/sel unique valable sur tous les marchés"], ["Aliments, poisson et bétail", "Production locale et échanges fluviaux", "Pas de production totale fiable pour l'empire"], ["Tissus et chevaux", "Importations et échanges régionaux", "Pas de registre annuel complet des importations"], ["Manuscrits", "Copistes, marchands, savants et bibliothèques", "Pas de recensement de tous les livres ou étudiants"]],
    cities: ["Gao", "Tombouctou", "Djenné", "Niger", "Bani / delta intérieur", "Dendi"], cityRoles: ["Gao : principale capitale politique", "Tombouctou : savoir et commerce", "Djenné : agriculture et commerce régional"],
    route: ["Maroc", "Sahara", "Tondibi", "Gao", "Départ en 1590", "Arrivée en 1591"],
    mapNote: "Schéma historique sans échelle. Le fleuve est simplifié ; les symboles montrent des connexions, pas des frontières précises ni toute l'étendue impériale.",
    invasionNote: "Direction générale, pas un itinéraire quotidien vérifié. Effectifs et détails tactiques varient selon les récits. Ahmad al-Mansur ordonna la campagne, Judar Pacha la commanda.",
    timelineNote: "Chroniques et récits modernes ne concordent pas sur tous les détails. Les dates approximatives le restent ; ces périodes ne signifient pas que toute résistance cessa en 1612.",
    economyNote: "Comparaison de réseaux, pas de flux chiffrés, de PIB ou de fortune royale. L'esclavage et le travail contraint sont abordés dans le texte, sans leur attribuer ici des prix marchands."
  },
  es: {
    titles: ["Songhai: cronología y límites de la evidencia", "Los protagonistas de los grandes cambios", "El mundo del Níger: tres funciones urbanas", "Cómo la economía conectaba regiones", "1590–1591: invasión a través del Sahara"],
    brand: "PRESDA DATA GRAPHICS", source: "Fuentes y contexto", date: "Fecha / período", event: "Acontecimiento", person: "Persona", role: "Función", goods: "Bienes / actividad", connection: "Conexión", limit: "Lo que las fuentes no miden", scroll: "Desplaza horizontalmente para leer la tabla completa.",
    timeline: [["Primer milenio", "Primeros asentamientos y comercio en Gao, documentados arqueológicamente"], ["1464–1492", "Reinado de Sunni Ali y expansión imperial"], ["1468", "Conquista de Tombuctú; cronología de la Universidad de Ciudad del Cabo"], ["Década de 1470", "Djenné bajo control songhai; fecha aproximada"], ["1493–1528", "Reinado de Askia Muhammad"], ["1495", "Tumba de los Askia, según UNESCO"], ["1496–1498", "Peregrinación de Askia Muhammad"], ["1528", "Deposición de Askia Muhammad"], ["1590", "Envío de la expedición saadí dirigida por Judar Pachá"], ["13 de marzo de 1591", "Tondibi: fecha del estudio de Nobili de 2022"], ["1591–1612", "Resistencia analizada por Kaba; coincide con la ocupación"], ["1594", "Exilio de destacados sabios de Tombuctú"]],
    rulers: [["Sunni Ali", "1464–1492", "Gobernante songhai; expansión militar"], ["Askia Muhammad", "1493–1528", "Gobernante songhai; administración y patronazgo intelectual"], ["Askia Ishaq II", "Tondibi, 1591", "Gobernante songhai cuyas fuerzas afrontaron la expedición"], ["Ahmad al-Mansur", "Invasión ordenada, 1590", "Sultán saadí de Marruecos; no dirigió Tondibi"], ["Judar Pachá", "Expedición, 1590–1591", "Comandante de campaña, no gobernante songhai"]],
    economy: [["Oro", "Intercambio transahariano hacia el norte", "Sin tonelaje imperial auditado ni valoración en dólares modernos"], ["Sal", "Abastecimiento sahariano a los mercados del Sahel", "Sin precio único oro/sal para todos los mercados"], ["Alimentos, pescado y ganado", "Producción local e intercambio fluvial", "Sin cifra fiable de producción imperial total"], ["Tejidos y caballos", "Importaciones e intercambio regional", "Sin registro anual completo de importaciones"], ["Manuscritos", "Copistas, comerciantes, sabios y bibliotecas", "Sin censo de todos los libros o estudiantes"]],
    cities: ["Gao", "Tombuctú", "Djenné", "Níger", "Bani / delta interior", "Dendi"], cityRoles: ["Gao: principal capital política", "Tombuctú: saber y comercio", "Djenné: agricultura y comercio regional"],
    route: ["Marruecos", "Sahara", "Tondibi", "Gao", "Salida en 1590", "Llegada en 1591"],
    mapNote: "Esquema histórico sin escala. Río simplificado; los símbolos muestran conexiones, no fronteras precisas ni toda la extensión imperial.",
    invasionNote: "Dirección general, no itinerario diario verificado. Efectivos y detalles tácticos varían entre relatos. Ahmad al-Mansur ordenó la campaña y Judar Pachá la dirigió.",
    timelineNote: "Crónicas y relatos modernos no coinciden en cada detalle. Las fechas aproximadas siguen siendo aproximadas; estas etapas no implican que toda resistencia terminara en 1612.",
    economyNote: "Comparación de redes, no flujos cuantificados, PIB o patrimonio real. Esclavitud y trabajo forzoso se explican en el artículo, sin convertirlos aquí en precios de mercancías."
  },
  ar: {
    titles: ["سونغاي: التسلسل الزمني وحدوده", "شخصيات صنعت نقاط التحول", "عالم النيجر: ثلاثة أدوار حضرية", "كيف ربط الاقتصاد بين المناطق؟", "1590–1591: غزو عبر الصحراء"],
    brand: "رسوم بيانات بريسدا", source: "المصادر والسياق", date: "التاريخ / الفترة", event: "الحدث", person: "الشخصية", role: "الدور", goods: "السلع / النشاط", connection: "الرابط", limit: "ما لا تقيسه الأدلة", scroll: "مرر أفقيا لقراءة الجدول كاملا.",
    timeline: [["الألفية الأولى للميلاد", "استيطان وتجارة مبكران في منطقة غاو، تثبتهما الآثار"], ["1464–1492", "حكم سني علي والتوسع الإمبراطوري"], ["1468", "فتح تمبكتو وفق تسلسل جامعة كيب تاون"], ["سبعينيات القرن الخامس عشر", "خضوع جني لسونغاي؛ تاريخ تقريبي"], ["1493–1528", "حكم أسقيا محمد"], ["1495", "ضريح الأسقيا وفق تأريخ اليونسكو"], ["1496–1498", "حج أسقيا محمد"], ["1528", "عزل أسقيا محمد"], ["1590", "إرسال الحملة السعدية بقيادة جؤذر باشا"], ["13 مارس 1591", "تونديبي: التاريخ الوارد في بحث نوبيلي 2022"], ["1591–1612", "فترة المقاومة التي درسها كابا، متداخلة مع الاحتلال"], ["1594", "نفي علماء بارزين من تمبكتو"]],
    rulers: [["سني علي", "1464–1492", "حاكم سونغاي؛ التوسع العسكري"], ["أسقيا محمد", "1493–1528", "حاكم سونغاي؛ الإدارة ورعاية العلماء"], ["أسقيا إسحاق الثاني", "تونديبي، 1591", "حاكم سونغاي الذي واجهت قواته الحملة"], ["أحمد المنصور", "أمر الغزو، 1590", "سلطان المغرب السعدي؛ لم يقد تونديبي"], ["جؤذر باشا", "الحملة، 1590–1591", "قائد ميداني، وليس حاكما لسونغاي"]],
    economy: [["الذهب", "تبادل شمالا عبر الصحراء", "لا وزن إمبراطوري مدقق أو قيمة بالدولار المعاصر"], ["الملح", "إمداد صحراوي لأسواق الساحل", "لا سعر ذهب مقابل ملح واحد لكل الأسواق"], ["الغذاء والأسماك والماشية", "إنتاج محلي وتبادل نهري", "لا مجموع موثوق لإنتاج الإمبراطورية"], ["القماش والخيل", "واردات وتبادل إقليمي", "لا سجل سنوي كامل للواردات"], ["المخطوطات", "نساخ وتجار وعلماء ومكتبات", "لا تعداد لكل الكتب أو الطلاب"]],
    cities: ["غاو", "تمبكتو", "جني", "النيجر", "باني / الدلتا الداخلية", "دندي"], cityRoles: ["غاو: العاصمة السياسية الرئيسية", "تمبكتو: العلم والتجارة", "جني: الزراعة والتبادل الإقليمي"],
    route: ["المغرب", "الصحراء", "تونديبي", "غاو", "الانطلاق 1590", "الوصول 1591"],
    mapNote: "رسم تاريخي تخطيطي بلا مقياس. مجرى النهر مبسط؛ الرموز تبين الروابط، لا حدودا دقيقة أو كامل مساحة الإمبراطورية.",
    invasionNote: "اتجاه عام، وليس مسارا يوميا موثقا. تختلف أعداد الجنود والتفاصيل التكتيكية بين الروايات. أمر أحمد المنصور بالحملة وقادها جؤذر باشا.",
    timelineNote: "لا تتفق الأخبار والروايات الحديثة على كل التفاصيل. تظل التواريخ التقريبية تقريبية؛ ولا يعني التداخل انتهاء كل مقاومة في 1612.",
    economyNote: "مقارنة شبكات، لا تدفقات مقيسة أو ناتج اقتصادي أو ثروة ملكية. يناقش المقال الاسترقاق والعمل القسري دون تحويلهما هنا إلى أسعار سلع."
  }
};
const links = {
  overview: "https://www.cambridge.org/core/journals/history-in-africa/article/abs/rulers-scholars-and-invaders-a-select-bibliography-of-the-songhay-empire/29DEEA09EBD992FA4D00BB6BB06F386B",
  invasion: "https://www.cambridge.org/core/journals/journal-of-african-history/article/abs/archers-musketeers-and-mosquitoes-the-moroccan-invasion-of-the-sudan-and-the-songhay-resistance-15911612/7BE695BFE53648CF3324ED70F40512D6",
  archives: "https://www.cambridge.org/core/journals/history-in-africa/article/west-africa-seen-from-moroccan-manuscript-archives/50B3C6ADCF4B1783813680B0FB281B9D",
  trade: "https://www.metmuseum.org/essays/the-trans-saharan-gold-trade-7th-14th-century",
  cape: "https://tombouctoumanuscripts.uct.ac.za/overview/timbuktus-history"
};

export function SonghaiGraphics({ locale, kind }: { locale: Locale; kind: SonghaiGraphicKind }) {
  const t = copy[locale];
  const index = ["timeline", "rulers", "cities", "economy", "invasion"].indexOf(kind);
  const id = `songhai-${kind}-${locale}`;
  const note = kind === "timeline" ? t.timelineNote : kind === "economy" ? t.economyNote : kind === "invasion" ? t.invasionNote : kind === "cities" ? t.mapNote : "";
  const refs = kind === "invasion" ? [["Kaba (1981)", links.invasion], ["Nobili (2022)", links.archives]] : kind === "economy" ? [["Metropolitan Museum", links.trade], ["University of Cape Town", links.cape]] : kind === "cities" ? [["UNESCO: Gao", "https://whc.unesco.org/en/list/1139/"], ["UNESCO: Timbuktu", "https://whc.unesco.org/en/list/119/"], ["UNESCO: Djenné", "https://whc.unesco.org/en/list/116/"]] : [["Singleton (2004)", links.overview], ["University of Cape Town", links.cape], ["Nobili (2022)", links.archives]];
  const table = (headers: string[], rows: string[][]) => <><p className="mt-4 text-xs text-white/70">{t.scroll}</p><div role="region" aria-label={t.titles[index]} tabIndex={0} className="mt-2 overflow-x-auto focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#D9AD55]"><table className="w-full min-w-[560px] border-collapse text-sm"><caption className="sr-only">{t.titles[index]}</caption><thead><tr>{headers.map(h => <th key={h} scope="col" className="border-b border-white/30 p-3 text-start">{h}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{r.map((v, j) => j === 0 ? <th key={j} scope="row" className="border-b border-white/15 p-3 text-start font-medium">{v}</th> : <td key={j} className="border-b border-white/15 p-3 text-start leading-relaxed"><bdi>{v}</bdi></td>)}</tr>)}</tbody></table></div></>;
  const label = (x: number, y: number, text: string, anchor: "start" | "middle" | "end" = "middle") => <text x={x} y={y} textAnchor={anchor} direction={locale === "ar" ? "rtl" : "ltr"} fill="#FFFFFF" fontSize="19" fontFamily="inherit">{text}</text>;
  return <figure dir={locale === "ar" ? "rtl" : "ltr"} aria-labelledby={id} data-songhai-graphic={kind} className="my-8 min-w-0 rounded-2xl border border-white/15 bg-[#10131A] p-4 text-white sm:p-6">
    <p className="font-display text-[11px] font-bold tracking-wider text-[#D9AD55]">{t.brand}</p>
    <h3 id={id} className="mt-2 font-display text-xl font-bold leading-snug sm:text-2xl">{t.titles[index]}</h3>
    {kind === "timeline" && <ol className="mt-5 space-y-3">{t.timeline.map(([date, event], i) => <li key={i} className="grid gap-1 border-s-2 border-[#D9AD55]/50 ps-4 sm:grid-cols-[160px_1fr] sm:gap-4"><span className="font-display text-sm font-semibold text-[#D9AD55]"><bdi>{date}</bdi></span><span className="text-sm leading-relaxed">{event}</span></li>)}</ol>}
    {kind === "rulers" && table([t.person, t.date, t.role], t.rulers)}
    {kind === "economy" && table([t.goods, t.connection, t.limit], t.economy)}
    {kind === "cities" && <><svg role="img" aria-labelledby={`${id}-svg-title ${id}-svg-desc`} viewBox="0 0 480 350" className="mx-auto mt-4 h-auto w-full max-w-2xl" style={{ direction: "ltr" }}><title id={`${id}-svg-title`}>{t.titles[index]}</title><desc id={`${id}-svg-desc`}>{t.mapNote} {t.cityRoles.join(". ")}</desc><path d="M 30 312 Q 98 286 132 252 Q 157 207 210 174 Q 240 119 297 151 Q 336 169 377 203 Q 410 256 440 324" fill="none" stroke="#85B5CB" strokeWidth="7" /><path d="M 82 279 Q 111 274 132 252" fill="none" stroke="#85B5CB" strokeWidth="4"/><circle cx="82" cy="279" r="8" fill="#D9AD55" stroke="#FFFFFF" strokeWidth="2"/><circle cx="249" cy="142" r="8" fill="#D9AD55" stroke="#FFFFFF" strokeWidth="2"/><rect x="369" y="195" width="16" height="16" fill="#E53935" stroke="#FFFFFF" strokeWidth="2"/>{label(378,180,t.cities[0])}{label(245,109,t.cities[1])}{label(75,312,t.cities[2])}{label(135,176,t.cities[3])}{label(124,342,t.cities[4])}{label(405,306,t.cities[5])}</svg><ul className="mt-3 space-y-2 text-sm leading-relaxed">{t.cityRoles.map((r, i) => <li key={r} className="flex items-start gap-3"><span aria-hidden="true" className={`mt-1.5 h-2.5 w-2.5 shrink-0 ${i === 0 ? "bg-[#E53935]" : "rounded-full bg-[#D9AD55]"}`} /><span>{r}</span></li>)}</ul></>}
    {kind === "invasion" && <svg role="img" aria-labelledby={`${id}-svg-title ${id}-svg-desc`} viewBox="0 0 480 350" className="mx-auto mt-4 h-auto w-full max-w-2xl" style={{ direction: "ltr" }}><title id={`${id}-svg-title`}>{t.titles[index]}</title><desc id={`${id}-svg-desc`}>{t.invasionNote}</desc><path d="M 40 100 Q 147 65 222 110 Q 290 153 330 212 Q 359 233 440 258" fill="none" stroke="#D9AD55" strokeWidth="2" strokeDasharray="6 8" opacity=".5"/><path d="M 155 58 Q 205 130 273 190 Q 327 221 343 257" fill="none" stroke="#E53935" strokeWidth="4" strokeDasharray="8 6"/><path d="M 334 245 L 343 259 L 349 242" fill="none" stroke="#E53935" strokeWidth="3"/><circle cx="155" cy="58" r="7" fill="#D9AD55"/><circle cx="332" cy="245" r="7" fill="#FFFFFF"/><rect x="345" y="280" width="14" height="14" fill="#E53935" stroke="#FFFFFF"/>{label(145,32,t.route[0])}{label(242,151,t.route[1])}{label(387,231,t.route[2])}{label(365,320,t.route[3])}{label(115,102,t.route[4])}{label(301,345,t.route[5])}</svg>}
    <figcaption className="mt-4 border-t border-white/15 pt-4 text-sm leading-relaxed text-white/75">{note && <p>{note}</p>}<p className="mt-2">{t.source}: {refs.map(([name,url], i) => <span key={url}>{i > 0 ? " · " : ""}<a href={url} className="underline underline-offset-4 hover:text-white">{name}</a></span>)}</p></figcaption>
  </figure>;
}
