import type { Locale } from "@/lib/i18n/routing";

// Historical nominal values, not 2026 appraisals. Native auction currencies
// remain authoritative; published dollar equivalents only order this selection.
export const watchPriceRows = [
  { name: "Graff Hallucination", year: "2014", type: "wrist", amount: "US$55,000,000", equivalent: "", basis: "launch", period: "2014", source: "https://www.jckonline.com/editorial-article/graff-unveils-55-million-hallucination-most-valuable-watch-ever-created/", photo: "https://www.atpress.ne.jp/news/45033", photoKind: "manufacturer" },
  { name: "Graff The Fascination", year: "2015", type: "wrist", amount: "US$40,000,000", equivalent: "", basis: "launch", period: "2015", source: "https://www.jckonline.com/editorial-article/graff-unveils-40-million-watch-at-baselworld/", photo: "https://www.thejewelleryeditor.com/shop/product/graff-fascination-15296-carat-transformable-diamond-watch/", photoKind: "editorial" },
  { name: "Patek Philippe Grandmaster Chime 6300A-010", year: "2019", type: "wrist", amount: "CHF 31,000,000", equivalent: "≈ US$31.1m", basis: "charity", period: "2019-11-09", source: "https://www.guinnessworldrecords.com/world-records/500098-most-expensive-wrist-watch-sold-at-auction", photo: "https://www.christies.com/en/lot/lot-6227458", photoKind: "auction" },
  { name: "Chopard 201-Carat", year: "2000", type: "wrist", amount: "US$25,000,000", equivalent: "", basis: "valuation", period: "", source: "https://www.sothebys.com/en/sell/watches/chopard", photo: "https://lux-life.digital/2016-chopard-201-carat-watch/", photoKind: "editorial" },
  { name: "Patek Philippe Henry Graves Jr. Supercomplication", year: "1932 / 1933", type: "pocket", amount: "CHF 23,237,000", equivalent: "≈ US$24m", basis: "auction", period: "2014-11-11", source: "https://www.sothebys.com/en/articles/the-four-most-complicated-watches-patek-philippe-has-ever-made", photo: "https://www.sothebys.com/en/auctions/ecatalogue/2014/important-watches-ge1404/lot.345.html", photoKind: "auction" },
  { name: "Jacob & Co. Billionaire Timeless Treasure", year: "2023", type: "wrist", amount: "US$20,000,000", equivalent: "", basis: "reported", period: "2023", source: "https://www.forbes.com.au/life/watches/jacob-co-drop-20-million-billionaire-timeless-treasure-watch/", photo: "https://jacobandco.jp/timepieces/billionaire-timeless-treasure/", photoKind: "manufacturer" },
  { name: "Jacob & Co. The Billionaire", year: "2015*", type: "wrist", amount: "US$18,000,000", equivalent: "", basis: "reported", period: "2015", source: "https://www.hautetime.com/jacob-co-unveils-18-million-diamond-watch-with-tourbillon/", photo: "https://www.hautetime.com/jacob-co-unveils-18-million-diamond-watch-with-tourbillon/", photoKind: "editorial" },
  { name: "Rolex Paul Newman Daytona 6239", year: "1968", type: "wrist", amount: "US$17,752,500", equivalent: "", basis: "auction", period: "2017-10-26", source: "https://www.phillips.com/detail/rolex/100049", photo: "https://www.phillips.com/detail/rolex/100049", photoKind: "auction" },
  { name: "Patek Philippe 1518, steel, case 508473", year: "1943", type: "wrist", amount: "CHF 14,190,000", equivalent: "US$17,631,075", basis: "auction", period: "2025-11", source: "https://www.phillips.com/detail/patek-philippe/222585", photo: "https://www.phillips.com/detail/patek-philippe/222585", photoKind: "auction" },
  { name: "Patek Philippe 6301A-010", year: "2024", type: "wrist", amount: "CHF 15,700,000", equivalent: "≈ US$17.3m", basis: "charity", period: "2024-05-10", source: "https://www.christies.com/en/stories/the-six-most-expensive-wristwatches-sold-at-christie's-f7b41987b20e4170ad705545044df87f", photo: "https://www.christies.com/en/lot/lot-6481406", photoKind: "auction" },
] as const;

const copy = {
  en: { title: "Top 10: what the price actually represents", date: "Sources checked October 10, 2026", headers: ["Position", "Watch / creation year", "Type", "Documented figure", "Evidence / price date", "Authentic photographs"], wrist: "Wristwatch", pocket: "Pocket watch", source: "Price source", manufacturer: "Manufacturer photographs", auctionPhoto: "Auction-house photographs", editorial: "Identified editorial photographs", launch: "Advertised launch value; no verified sale", reported: "Reported launch price; not an auction result", valuation: "Sotheby’s stated valuation; appraisal date not supplied", auction: "Published realised auction result", charity: "Charity auction result", note: "Selection ordered by historical nominal dollar figures, not ten confirmed sales or current appraisals. CHF is the actual sale currency where shown; dollar equivalents are those published by the sources, not conversions at today’s rate. The 6301A ranks above the 1518 in CHF but below it using those historical dollar equivalents.", foot: "* The original Billionaire appears in dated 2015 first-hand reporting. The manufacturer’s later history gives 2016. Graves: completed 1932, delivered 1933. Ordinary auction totals include premium where reported; the 2019 Only Watch record had no buyer’s premium. The charity and commercial results are not identical price settings. Photographs open on their source websites; no image-reuse licence is claimed." },
  fr: { title: "Top 10 : ce que représente réellement le prix", date: "Sources vérifiées le 10 octobre 2026", headers: ["Position", "Montre / année de création", "Type", "Montant documenté", "Preuve / date du prix", "Photographies authentiques"], wrist: "Montre-bracelet", pocket: "Montre de poche", source: "Source du prix", manufacturer: "Photographies du fabricant", auctionPhoto: "Photographies de la maison de vente", editorial: "Photographies éditoriales identifiées", launch: "Valeur annoncée au lancement ; pas de vente vérifiée", reported: "Prix de lancement publié ; pas une adjudication", valuation: "Évaluation de Sotheby’s ; date d’expertise non fournie", auction: "Résultat réalisé aux enchères", charity: "Résultat d’enchères caritatives", note: "Sélection ordonnée par montants nominaux historiques en dollars, pas dix ventes confirmées ou expertises actuelles. Le CHF est la devise de vente indiquée ; les équivalents en dollars sont ceux des sources, pas des conversions au taux actuel. La 6301A dépasse la 1518 en CHF mais passe derrière selon ces équivalents historiques.", foot: "* Billionaire apparaît dans un reportage direct daté de 2015 ; l’historique ultérieur du fabricant donne 2016. Graves : achevée en 1932, livrée en 1933. Les résultats ordinaires comprennent les commissions lorsqu’elles sont indiquées ; le record Only Watch 2019 n’en comportait pas. Ventes caritatives et commerciales n’ont pas un contexte identique. Les photos s’ouvrent sur les sites sources ; aucune licence de réutilisation n’est revendiquée." },
  es: { title: "Top 10: qué representa realmente el precio", date: "Fuentes verificadas el 10 de octubre de 2026", headers: ["Posición", "Reloj / año de creación", "Tipo", "Importe documentado", "Evidencia / fecha del precio", "Fotografías auténticas"], wrist: "Reloj de pulsera", pocket: "Reloj de bolsillo", source: "Fuente del precio", manufacturer: "Fotografías del fabricante", auctionPhoto: "Fotografías de la casa de subastas", editorial: "Fotografías editoriales identificadas", launch: "Valor anunciado al lanzamiento; venta no verificada", reported: "Precio de lanzamiento publicado; no subasta", valuation: "Valoración de Sotheby’s; fecha de tasación no indicada", auction: "Resultado realizado en subasta", charity: "Resultado de subasta benéfica", note: "Selección ordenada por cifras nominales históricas en dólares, no diez ventas confirmadas o tasaciones actuales. CHF es la divisa real cuando se muestra; los equivalentes en dólares proceden de las fuentes, no del tipo de cambio actual. El 6301A supera al 1518 en CHF pero queda por debajo con esos equivalentes históricos.", foot: "* El Billionaire aparece en cobertura directa fechada en 2015; la historia posterior del fabricante indica 2016. Graves: terminado en 1932, entregado en 1933. Los resultados ordinarios incluyen comisión cuando se indica; el récord de Only Watch 2019 no la tuvo. Los contextos de venta benéfica y comercial son distintos. Las fotografías se abren en sus sitios de origen; no se afirma una licencia de reutilización." },
  ar: { title: "قائمة العشر: ما الذي يعنيه السعر فعلاً؟", date: "مصادر جرى التحقق منها في 10 أكتوبر 2026", headers: ["الترتيب", "الساعة / سنة الإنشاء", "النوع", "المبلغ الموثق", "الدليل / تاريخ السعر", "الصور الأصلية"], wrist: "ساعة يد", pocket: "ساعة جيب", source: "مصدر السعر", manufacturer: "صور الشركة المصنعة", auctionPhoto: "صور بيت المزاد", editorial: "صور تحريرية بمصدر محدد", launch: "قيمة معلنة عند الإطلاق؛ لا بيع موثق", reported: "سعر إطلاق منشور؛ ليس نتيجة مزاد", valuation: "تقييم Sotheby’s؛ تاريخ التقييم غير محدد", auction: "نتيجة بيع منشورة في المزاد", charity: "نتيجة مزاد خيري", note: "اختيار مرتب وفق مبالغ الدولار الاسمية التاريخية، وليس عشر مبيعات مؤكدة أو تقييمات حالية. الفرنك هو عملة البيع الفعلية حيث يذكر؛ معادلات الدولار من المصادر، وليست تحويلاً بسعر اليوم. تتقدم 6301A على 1518 بالفرنك وتتأخر وفق معادلات الدولار التاريخية.", foot: "* توثق تغطية مباشرة مؤرخة إطلاق Billionaire في 2015، بينما يذكر تاريخ الشركة اللاحق 2016. Graves: اكتملت في 1932 وسلمت في 1933. تشمل نتائج المزاد العادي العمولة حيث تذكر؛ لم يفرض رقم Only Watch لعام 2019 عمولة مشتري. سياق المزاد الخيري مختلف عن التجاري. تفتح الصور على مواقع مصادرها، ولا ندعي امتلاك ترخيص إعادة استخدامها." },
};

export function WatchPriceComparison({ locale }: { locale: Locale }) {
  const c = copy[locale];
  return <figure id="watch-price-comparison" dir={locale === "ar" ? "rtl" : "ltr"} aria-labelledby="watch-price-comparison-title" style={{ display: "flow-root" }} className="my-8 min-w-0 scroll-mt-28 rounded-xl border border-white/15 bg-[#101010] p-4 text-white sm:p-6">
    <figcaption>
      <p className="mb-3 text-xs font-bold uppercase text-[#FF1A1A]">PRESDA Data Graphics</p>
      <h3 id="watch-price-comparison-title" className="text-xl font-bold text-[#e9bd65]">{c.title}</h3>
      <p className="mt-2 text-xs text-white/70">{c.date}</p>
      <p id="watch-price-comparison-note" className="my-4 text-sm leading-6 text-white/85">{c.note}</p>
    </figcaption>
    <div role="region" aria-label={c.title} aria-describedby="watch-price-comparison-note" tabIndex={0} className="overflow-x-auto focus:outline focus:outline-2 focus:outline-offset-2 focus:outline-[#e9bd65]">
      <table className="w-full min-w-[980px] text-start text-sm leading-6">
        <thead><tr>{c.headers.map(h => <th scope="col" key={h} className="border-b border-white/25 p-3 text-start align-bottom font-bold">{h}</th>)}</tr></thead>
        <tbody>{watchPriceRows.map((r, i) => <tr key={r.name}>
          <td className="border-b border-white/10 p-3 align-top text-[#e9bd65]"><bdi>{i + 1}</bdi></td>
          <th scope="row" className="max-w-[240px] border-b border-white/10 p-3 text-start align-top font-medium"><bdi>{r.name}</bdi><span className="block text-xs text-white/65"><bdi>{r.year}</bdi></span></th>
          <td className="border-b border-white/10 p-3 align-top">{c[r.type]}</td>
          <td className="border-b border-white/10 p-3 align-top"><bdi className="whitespace-nowrap font-semibold">{r.amount}</bdi>{r.equivalent && <span className="block text-xs text-white/65"><bdi>{r.equivalent}</bdi></span>}</td>
          <td className="max-w-[220px] border-b border-white/10 p-3 align-top">{c[r.basis]}{r.period && <span className="block"><bdi>{r.period}</bdi></span>}<a href={r.source} aria-label={`${c.source}: ${r.name}`} className="block text-xs underline decoration-[#e9bd65] underline-offset-4">{c.source}</a></td>
          <td className="border-b border-white/10 p-3 align-top"><a href={r.photo} aria-label={`${r.photoKind === "auction" ? c.auctionPhoto : c[r.photoKind]}: ${r.name}`} className="inline-block rounded border border-[#e9bd65]/40 px-3 py-2 text-xs font-medium text-[#e9bd65] underline underline-offset-4">{r.photoKind === "auction" ? c.auctionPhoto : c[r.photoKind]}</a></td>
        </tr>)}</tbody>
      </table>
    </div>
    <p className="mt-4 text-xs leading-5 text-white/70">{c.foot}</p>
  </figure>;
}
